use surrealdb::engine::local::Db;
use surrealdb::Surreal;
use tracing::info;

use crate::error::MythicError;

/// Defines the complete SurrealDB schema for Mythic.
/// This function is idempotent — safe to call on every app startup.
/// SurrealDB's DEFINE statements are no-ops when the definition already exists.
pub async fn define_schema(db: &Surreal<Db>) -> Result<(), MythicError> {
    // ── 1. characters ───────────────────────────────────────────────────
    info!("  schema: characters...");
    db.query("
        DEFINE TABLE IF NOT EXISTS characters SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS name       ON characters TYPE string ASSERT $value != NONE;
        DEFINE FIELD IF NOT EXISTS spec       ON characters TYPE string DEFAULT 'chara_card_v2';
        DEFINE FIELD IF NOT EXISTS data       ON characters TYPE object FLEXIBLE;
        DEFINE FIELD IF NOT EXISTS avatar_path ON characters TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS created_at ON characters TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS updated_at ON characters TYPE datetime DEFAULT time::now();

        -- 'gallery' = a real standalone character the user created/imported;
        -- 'npc' = auto-generated by the story-driven NPC detector, scoped to
        -- the conversation that spawned it until the user promotes it.
        DEFINE FIELD IF NOT EXISTS origin ON characters TYPE string DEFAULT 'gallery' ASSERT $value IN ['gallery', 'npc'];
        -- Only meaningful for auto-generated portraits — 'pending_review' means
        -- the image exists but hasn't been approved yet (see settings toggle).
        DEFINE FIELD IF NOT EXISTS portrait_status ON characters TYPE string DEFAULT 'approved' ASSERT $value IN ['approved', 'pending_review'];
        -- False only for a freshly auto-generated NPC profile the user hasn't
        -- opened yet — drives the needs-attention indicator.
        DEFINE FIELD IF NOT EXISTS profile_reviewed ON characters TYPE bool DEFAULT true;
        -- Soft-delete: set when moved to Trash, cleared on Restore. A NONE
        -- value means the character is live; list_characters filters these
        -- out by default so trashed characters vanish from Gallery without
        -- actually losing data until the user empties the Trash.
        DEFINE FIELD IF NOT EXISTS deleted_at ON characters TYPE option<datetime>;

        DEFINE INDEX IF NOT EXISTS idx_characters_updated ON characters FIELDS updated_at;
        DEFINE INDEX IF NOT EXISTS idx_characters_origin ON characters FIELDS origin;
        DEFINE INDEX IF NOT EXISTS idx_characters_deleted ON characters FIELDS deleted_at;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:characters: {}", e)))?;

    // ── ai_horde_model_info ─────────────────────────────────────────────
    // Locally cached capability metadata for AI Horde image models — merged
    // from the live /v2/status/models endpoint (worker_count) and the
    // static Haidra-Org model reference (baseline/inpainting/nsfw), so the
    // frontend can show/hide img2img options per model without a live
    // network round-trip on every render. Refreshed opportunistically
    // whenever the AI Horde model list is fetched.
    info!("  schema: ai_horde_model_info...");
    db.query("
        DEFINE TABLE IF NOT EXISTS ai_horde_model_info SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS name             ON ai_horde_model_info TYPE string;
        DEFINE FIELD IF NOT EXISTS baseline          ON ai_horde_model_info TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS inpainting        ON ai_horde_model_info TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS nsfw              ON ai_horde_model_info TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS style              ON ai_horde_model_info TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS img2img_supported ON ai_horde_model_info TYPE bool DEFAULT true;
        DEFINE FIELD IF NOT EXISTS worker_count      ON ai_horde_model_info TYPE int DEFAULT 0;
        DEFINE FIELD IF NOT EXISTS updated_at        ON ai_horde_model_info TYPE datetime DEFAULT time::now();
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:ai_horde_model_info: {}", e)))?;

    // ── image_presets ────────────────────────────────────────────────────
    // Defined before `conversations` since that table references it via
    // `image_preset_id`.
    info!("  schema: image_presets...");
    db.query("
        DEFINE TABLE IF NOT EXISTS image_presets SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS name            ON image_presets TYPE string;
        DEFINE FIELD IF NOT EXISTS model            ON image_presets TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS sampler_name     ON image_presets TYPE string DEFAULT 'k_euler_a';
        DEFINE FIELD IF NOT EXISTS cfg_scale        ON image_presets TYPE float DEFAULT 7.5;
        DEFINE FIELD IF NOT EXISTS steps            ON image_presets TYPE int DEFAULT 30;
        DEFINE FIELD IF NOT EXISTS karras           ON image_presets TYPE bool DEFAULT true;
        DEFINE FIELD IF NOT EXISTS style            ON image_presets TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS negative_prompt  ON image_presets TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS clip_skip        ON image_presets TYPE option<int>;
        DEFINE FIELD IF NOT EXISTS post_processing  ON image_presets TYPE array<string> DEFAULT [];
        DEFINE FIELD IF NOT EXISTS hires_fix        ON image_presets TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS hires_fix_denoising_strength ON image_presets TYPE option<float>;
        DEFINE FIELD IF NOT EXISTS is_default       ON image_presets TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS created_at       ON image_presets TYPE datetime DEFAULT time::now();
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:image_presets: {}", e)))?;

    // ── personas ─────────────────────────────────────────────────────────
    // User-controlled profiles (the player's own stand-in), same
    // CharacterCardV2-shaped `data` JSON as `characters` but with none of
    // the NPC-pipeline-only fields. Defined before `conversations` since
    // that table references it via `persona_id`.
    info!("  schema: personas...");
    db.query(
        "
        DEFINE TABLE IF NOT EXISTS personas SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS name        ON personas TYPE string ASSERT $value != NONE;
        DEFINE FIELD IF NOT EXISTS spec        ON personas TYPE string DEFAULT 'chara_card_v2';
        DEFINE FIELD IF NOT EXISTS data        ON personas TYPE object FLEXIBLE;
        DEFINE FIELD IF NOT EXISTS avatar_path ON personas TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS created_at  ON personas TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS updated_at  ON personas TYPE datetime DEFAULT time::now();
        -- Soft-delete — see the matching comment on characters.deleted_at.
        DEFINE FIELD IF NOT EXISTS deleted_at  ON personas TYPE option<datetime>;

        DEFINE INDEX IF NOT EXISTS idx_personas_updated ON personas FIELDS updated_at;
        DEFINE INDEX IF NOT EXISTS idx_personas_deleted ON personas FIELDS deleted_at;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:personas: {}", e)))?;

    // ── 2. conversations ────────────────────────────────────────────────
    info!("  schema: conversations...");
    db.query("
        DEFINE TABLE IF NOT EXISTS conversations SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS title                    ON conversations TYPE string;
        DEFINE FIELD IF NOT EXISTS character_id             ON conversations TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS active_message_id        ON conversations TYPE option<record<messages>>;
        DEFINE FIELD IF NOT EXISTS memory_scope             ON conversations TYPE string DEFAULT 'character'
            ASSERT $value IN ['character', 'conversation', 'none'];
        DEFINE FIELD IF NOT EXISTS shared_character_ids     ON conversations TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS parent_conversation_id   ON conversations TYPE option<record<conversations>>;
        DEFINE FIELD IF NOT EXISTS branch_point_message_id  ON conversations TYPE option<record<messages>>;
        DEFINE FIELD IF NOT EXISTS image_preset_id          ON conversations TYPE option<record<image_presets>>;
        DEFINE FIELD IF NOT EXISTS persona_id               ON conversations TYPE option<record<personas>>;
        DEFINE FIELD IF NOT EXISTS created_at               ON conversations TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS updated_at               ON conversations TYPE datetime DEFAULT time::now();
        -- Soft-delete — see the matching comment on characters.deleted_at.
        DEFINE FIELD IF NOT EXISTS deleted_at                ON conversations TYPE option<datetime>;

        DEFINE INDEX IF NOT EXISTS idx_conversations_character ON conversations FIELDS character_id;
        DEFINE INDEX IF NOT EXISTS idx_conversations_updated   ON conversations FIELDS updated_at;
        DEFINE INDEX IF NOT EXISTS idx_conversations_persona   ON conversations FIELDS persona_id;
        DEFINE INDEX IF NOT EXISTS idx_conversations_deleted   ON conversations FIELDS deleted_at;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:conversations: {}", e)))?;

    // ── 3. messages ─────────────────────────────────────────────────────
    info!("  schema: messages...");
    db.query(
        "
        DEFINE TABLE IF NOT EXISTS messages SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id ON messages TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS role             ON messages TYPE string
            ASSERT $value IN ['user', 'assistant', 'system'];
        DEFINE FIELD IF NOT EXISTS content          ON messages TYPE string;
        DEFINE FIELD IF NOT EXISTS parent_id        ON messages TYPE option<record<messages>>;
        DEFINE FIELD IF NOT EXISTS metadata         ON messages TYPE option<object> FLEXIBLE;
        DEFINE FIELD IF NOT EXISTS character_id     ON messages TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS character_name   ON messages TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS created_at       ON messages TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS reasoning        ON messages TYPE option<string>;

        DEFINE INDEX IF NOT EXISTS idx_messages_conversation ON messages FIELDS conversation_id;
        DEFINE INDEX IF NOT EXISTS idx_messages_parent       ON messages FIELDS parent_id;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:messages: {}", e)))?;

    // FTS analyzer and index (separate query to isolate errors)
    info!("  schema: messages FTS...");
    db.query("
        DEFINE ANALYZER IF NOT EXISTS msg_analyzer TOKENIZERS class FILTERS lowercase, edgengram(2, 15);
        DEFINE INDEX IF NOT EXISTS idx_messages_fts ON messages FIELDS content
            FULLTEXT ANALYZER msg_analyzer BM25;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:messages_fts: {}", e)))?;

    // ── 4. memories ─────────────────────────────────────────────────────
    info!("  schema: memories...");
    db.query(
        "
        DEFINE TABLE IF NOT EXISTS memories SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS character_id    ON memories TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS conversation_id ON memories TYPE option<record<conversations>>;
        DEFINE FIELD IF NOT EXISTS content          ON memories TYPE string;
        DEFINE FIELD IF NOT EXISTS source           ON memories TYPE string DEFAULT 'user'
            ASSERT $value IN ['user', 'auto'];
        DEFINE FIELD IF NOT EXISTS parent_id        ON memories TYPE option<record<memories>>;
        DEFINE FIELD IF NOT EXISTS version          ON memories TYPE int DEFAULT 1;
        DEFINE FIELD IF NOT EXISTS is_canon         ON memories TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS created_at       ON memories TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS importance       ON memories TYPE int DEFAULT 5
            ASSERT $value >= 1 AND $value <= 10;
        DEFINE FIELD IF NOT EXISTS last_accessed    ON memories TYPE option<datetime>;
        DEFINE FIELD IF NOT EXISTS access_count     ON memories TYPE int DEFAULT 0;

        DEFINE INDEX IF NOT EXISTS idx_memories_character    ON memories FIELDS character_id;
        DEFINE INDEX IF NOT EXISTS idx_memories_conversation ON memories FIELDS conversation_id;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:memories: {}", e)))?;

    // FTS index on memory content — reuses the same analyzer as messages so
    // hybrid (BM25 + vector) retrieval works identically for both.
    info!("  schema: memories FTS...");
    db.query(
        "
        DEFINE INDEX IF NOT EXISTS idx_memories_fts ON memories FIELDS content
            FULLTEXT ANALYZER msg_analyzer BM25;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:memories_fts: {}", e)))?;

    // ── 5. memory_link (graph edge table) ───────────────────────────────
    info!("  schema: memory_link...");
    db.query("
        DEFINE TABLE IF NOT EXISTS memory_link TYPE RELATION FROM memories TO conversations SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS link_type    ON memory_link TYPE string ASSERT $value IN ['copy', 'sync'];
        DEFINE FIELD IF NOT EXISTS direction    ON memory_link TYPE string ASSERT $value IN ['one_way', 'two_way'];
        DEFINE FIELD IF NOT EXISTS sync_mode    ON memory_link TYPE string ASSERT $value IN ['auto', 'manual'];
        DEFINE FIELD IF NOT EXISTS linked_memory_id ON memory_link TYPE option<record<memories>>;
        DEFINE FIELD IF NOT EXISTS created_at   ON memory_link TYPE datetime DEFAULT time::now();
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:memory_link: {}", e)))?;

    // memory_link event
    info!("  schema: memory_link event...");
    db.query(
        "
        DEFINE EVENT IF NOT EXISTS enforce_copy_direction ON TABLE memory_link
            WHEN $event = 'CREATE' OR $event = 'UPDATE' THEN {
            IF $after.link_type = 'copy' AND $after.direction != 'one_way' {
                THROW 'Copy links must be one_way';
            };
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:memory_link_event: {}", e)))?;

    // ── 6. lorebook_entries ─────────────────────────────────────────────
    info!("  schema: lorebook_entries...");
    db.query("
        DEFINE TABLE IF NOT EXISTS lorebook_entries SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS character_id    ON lorebook_entries TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS keys            ON lorebook_entries TYPE array;
        DEFINE FIELD IF NOT EXISTS content         ON lorebook_entries TYPE string;
        DEFINE FIELD IF NOT EXISTS enabled         ON lorebook_entries TYPE bool DEFAULT true;
        DEFINE FIELD IF NOT EXISTS always_active   ON lorebook_entries TYPE bool DEFAULT false;
        DEFINE FIELD IF NOT EXISTS priority        ON lorebook_entries TYPE int DEFAULT 10;
        DEFINE FIELD IF NOT EXISTS insertion_order ON lorebook_entries TYPE int DEFAULT 100;
        DEFINE FIELD IF NOT EXISTS name            ON lorebook_entries TYPE option<string>;

        DEFINE INDEX IF NOT EXISTS idx_lorebook_character ON lorebook_entries FIELDS character_id;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:lorebook: {}", e)))?;

    // ── 7. provider_configs ─────────────────────────────────────────────
    info!("  schema: provider_configs...");
    db.query(
        "
        DEFINE TABLE IF NOT EXISTS provider_configs SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS name          ON provider_configs TYPE string;
        DEFINE FIELD IF NOT EXISTS provider_type ON provider_configs TYPE string
            ASSERT $value IN ['llm', 'image', 'video'];
        DEFINE FIELD IF NOT EXISTS adapter       ON provider_configs TYPE string;
        DEFINE FIELD IF NOT EXISTS config        ON provider_configs TYPE object FLEXIBLE;
        DEFINE FIELD IF NOT EXISTS is_default    ON provider_configs TYPE bool DEFAULT false;

        DEFINE INDEX IF NOT EXISTS idx_provider_type ON provider_configs FIELDS provider_type;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:providers: {}", e)))?;

    // ── 8. enabled_models ───────────────────────────────────────────────
    info!("  schema: enabled_models...");
    db.query("
        DEFINE TABLE IF NOT EXISTS enabled_models SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS provider_id ON enabled_models TYPE record<provider_configs>;
        DEFINE FIELD IF NOT EXISTS model_id    ON enabled_models TYPE string;
        DEFINE FIELD IF NOT EXISTS model_type  ON enabled_models TYPE string DEFAULT 'llm';
        DEFINE FIELD IF NOT EXISTS enabled     ON enabled_models TYPE bool DEFAULT true;
        DEFINE FIELD IF NOT EXISTS created_at  ON enabled_models TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS updated_at  ON enabled_models TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_enabled_provider_model ON enabled_models FIELDS provider_id, model_id UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:enabled_models: {}", e)))?;

    // ── 9. scenes ───────────────────────────────────────────────────────
    info!("  schema: scenes...");
    db.query("
        DEFINE TABLE IF NOT EXISTS scenes SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id ON scenes TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS message_id      ON scenes TYPE option<record<messages>>;
        DEFINE FIELD IF NOT EXISTS media_type      ON scenes TYPE string ASSERT $value IN ['image', 'video'];
        DEFINE FIELD IF NOT EXISTS prompt           ON scenes TYPE string;
        DEFINE FIELD IF NOT EXISTS file_path        ON scenes TYPE string;
        DEFINE FIELD IF NOT EXISTS caption          ON scenes TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS metadata         ON scenes TYPE option<object> FLEXIBLE;
        DEFINE FIELD IF NOT EXISTS created_at       ON scenes TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_scenes_conversation ON scenes FIELDS conversation_id;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:scenes: {}", e)))?;

    // ── 10. scene_states ────────────────────────────────────────────────
    info!("  schema: scene_states...");
    db.query("
        DEFINE TABLE IF NOT EXISTS scene_states SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id      ON scene_states TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS location_name        ON scene_states TYPE string DEFAULT 'Unknown';
        DEFINE FIELD IF NOT EXISTS location_description ON scene_states TYPE string DEFAULT '';
        DEFINE FIELD IF NOT EXISTS time_period          ON scene_states TYPE string DEFAULT 'unspecified';
        DEFINE FIELD IF NOT EXISTS weather              ON scene_states TYPE string DEFAULT 'clear';
        DEFINE FIELD IF NOT EXISTS characters_present   ON scene_states TYPE array DEFAULT [];
        DEFINE FIELD IF NOT EXISTS ambient_details      ON scene_states TYPE string DEFAULT '';
        DEFINE FIELD IF NOT EXISTS scene_mood           ON scene_states TYPE string DEFAULT 'neutral';
        DEFINE FIELD IF NOT EXISTS updated_at           ON scene_states TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_ss_conversation ON scene_states FIELDS conversation_id UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:scene_states: {}", e)))?;

    // ── 10b. conversation_characters ────────────────────────────────────
    info!("  schema: conversation_characters...");
    db.query("
        DEFINE TABLE IF NOT EXISTS conversation_characters SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id ON conversation_characters TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS character_id    ON conversation_characters TYPE record<characters>;
        DEFINE FIELD IF NOT EXISTS role            ON conversation_characters TYPE string DEFAULT 'secondary';
        DEFINE FIELD IF NOT EXISTS talkativeness   ON conversation_characters TYPE int DEFAULT 50;
        DEFINE FIELD IF NOT EXISTS is_active       ON conversation_characters TYPE bool DEFAULT true;
        DEFINE FIELD IF NOT EXISTS character_name  ON conversation_characters TYPE string DEFAULT '';
        DEFINE FIELD IF NOT EXISTS created_at      ON conversation_characters TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_cc_unique ON conversation_characters FIELDS conversation_id, character_id UNIQUE;
        DEFINE INDEX IF NOT EXISTS idx_cc_conversation ON conversation_characters FIELDS conversation_id;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:conversation_characters: {}", e)))?;

    // ── 10c. npc_candidates ──────────────────────────────────────────────
    // Bookkeeping for the story-driven NPC detector's debounce: a name must
    // be tagged 'recurring'/'pivotal' across two SEPARATE detector passes
    // before a full profile gets generated.
    info!("  schema: npc_candidates...");
    db.query("
        DEFINE TABLE IF NOT EXISTS npc_candidates SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id        ON npc_candidates TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS candidate_key          ON npc_candidates TYPE string;
        DEFINE FIELD IF NOT EXISTS display_name           ON npc_candidates TYPE string;
        DEFINE FIELD IF NOT EXISTS tag                     ON npc_candidates TYPE string DEFAULT 'recurring';
        DEFINE FIELD IF NOT EXISTS pass_count              ON npc_candidates TYPE int DEFAULT 0;
        DEFINE FIELD IF NOT EXISTS status                  ON npc_candidates TYPE string DEFAULT 'pending';
        DEFINE FIELD IF NOT EXISTS resulting_character_id ON npc_candidates TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS first_seen_at           ON npc_candidates TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS last_seen_at            ON npc_candidates TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_npc_cand_unique ON npc_candidates FIELDS conversation_id, candidate_key UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:npc_candidates: {}", e)))?;

    // ── 10d. npc_detection_state ─────────────────────────────────────────
    // Per-conversation cadence tracking for the periodic (non-forced)
    // NPC-detection safety net.
    info!("  schema: npc_detection_state...");
    db.query("
        DEFINE TABLE IF NOT EXISTS npc_detection_state SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id         ON npc_detection_state TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS messages_since_scan     ON npc_detection_state TYPE int DEFAULT 0;
        DEFINE FIELD IF NOT EXISTS last_scanned_message_id ON npc_detection_state TYPE option<string>;
        DEFINE FIELD IF NOT EXISTS updated_at              ON npc_detection_state TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_npcstate_conv ON npc_detection_state FIELDS conversation_id UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:npc_detection_state: {}", e)))?;

    // ── 11. character_states ────────────────────────────────────────────
    info!("  schema: character_states...");
    db.query("
        DEFINE TABLE IF NOT EXISTS character_states SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS character_id    ON character_states TYPE record<characters>;
        DEFINE FIELD IF NOT EXISTS conversation_id ON character_states TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS mood             ON character_states TYPE int DEFAULT 50;
        DEFINE FIELD IF NOT EXISTS trust            ON character_states TYPE int DEFAULT 50;
        DEFINE FIELD IF NOT EXISTS arousal          ON character_states TYPE int DEFAULT 30;
        DEFINE FIELD IF NOT EXISTS dominant_emotion ON character_states TYPE string DEFAULT 'neutral';
        DEFINE FIELD IF NOT EXISTS state_summary    ON character_states TYPE string DEFAULT '';
        DEFINE FIELD IF NOT EXISTS updated_at       ON character_states TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_charstate_unique ON character_states FIELDS character_id, conversation_id UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:character_states: {}", e)))?;

    // ── 11. conversation_summaries ──────────────────────────────────────
    info!("  schema: conversation_summaries...");
    db.query("
        DEFINE TABLE IF NOT EXISTS conversation_summaries SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS conversation_id ON conversation_summaries TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS summary_text ON conversation_summaries TYPE string;
        DEFINE FIELD IF NOT EXISTS covered_message_count ON conversation_summaries TYPE int DEFAULT 0;
        DEFINE FIELD IF NOT EXISTS token_count ON conversation_summaries TYPE int DEFAULT 0;
        DEFINE FIELD IF NOT EXISTS window_start_message_id ON conversation_summaries TYPE option<record<messages>>;
        DEFINE FIELD IF NOT EXISTS created_at ON conversation_summaries TYPE datetime DEFAULT time::now();
        DEFINE FIELD IF NOT EXISTS updated_at ON conversation_summaries TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_summary_conversation ON conversation_summaries FIELDS conversation_id UNIQUE;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:conversation_summaries: {}", e)))?;

    // ── 12. message_embeddings ──────────────────────────────────────────
    info!("  schema: message_embeddings...");
    db.query("
        DEFINE TABLE IF NOT EXISTS message_embeddings SCHEMAFULL;

        DEFINE FIELD IF NOT EXISTS message_id ON message_embeddings TYPE record<messages>;
        DEFINE FIELD IF NOT EXISTS conversation_id ON message_embeddings TYPE record<conversations>;
        DEFINE FIELD IF NOT EXISTS embedding ON message_embeddings TYPE array<float>;
        DEFINE FIELD IF NOT EXISTS model_name ON message_embeddings TYPE string;
        DEFINE FIELD IF NOT EXISTS created_at ON message_embeddings TYPE datetime DEFAULT time::now();

        DEFINE INDEX IF NOT EXISTS idx_me_message ON message_embeddings FIELDS message_id UNIQUE;
        DEFINE INDEX IF NOT EXISTS idx_me_conversation ON message_embeddings FIELDS conversation_id;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:message_embeddings: {}", e)))?;

    // Add dimension field to track embedding dimensions per record
    info!("  schema: message_embeddings dimension field...");
    db.query(
        "
        DEFINE FIELD IF NOT EXISTS dimension ON message_embeddings TYPE int DEFAULT 0;
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:message_embeddings_dimension: {}", e)))?;

    // Add entry_type, character_id, source_id fields and indexes for RAG support
    info!("  schema: message_embeddings RAG fields...");
    db.query("
        DEFINE FIELD IF NOT EXISTS entry_type ON message_embeddings TYPE string DEFAULT 'message';
        DEFINE FIELD IF NOT EXISTS character_id ON message_embeddings TYPE option<record<characters>>;
        DEFINE FIELD IF NOT EXISTS source_id ON message_embeddings TYPE option<string>;

        DEFINE INDEX IF NOT EXISTS idx_me_character ON message_embeddings FIELDS character_id;
        DEFINE INDEX IF NOT EXISTS idx_me_entry_type ON message_embeddings FIELDS entry_type;
    ")
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:message_embeddings_rag: {}", e)))?;

    // NOTE: HNSW index is created dynamically via `ensure_vector_index()`
    // when the first embedding is stored, using the actual vector dimension.

    // ── Cascade delete events ───────────────────────────────────────────
    info!("  schema: cascade events...");
    db.query(
        "
        DEFINE EVENT IF NOT EXISTS cascade_character_delete ON TABLE characters
            WHEN $event = 'DELETE' THEN {
            DELETE FROM conversations WHERE character_id = $before.id;
            DELETE FROM memories WHERE character_id = $before.id;
            DELETE FROM lorebook_entries WHERE character_id = $before.id;
            -- A character can also be a *secondary/NPC* cast member of
            -- conversations it doesn't own (added via Group Cast or the
            -- auto-detection pipeline) — without this, those conversations
            -- keep a conversation_characters row pointing at a now-deleted
            -- character forever (a permanently broken roster entry).
            DELETE FROM conversation_characters WHERE character_id = $before.id;
            DELETE FROM character_states WHERE character_id = $before.id;
            DELETE FROM message_embeddings WHERE character_id = $before.id;
            DELETE FROM npc_candidates WHERE resulting_character_id = $before.id;
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:cascade_char: {}", e)))?;

    db.query(
        "
        DEFINE EVENT IF NOT EXISTS cascade_conversation_delete ON TABLE conversations
            WHEN $event = 'DELETE' THEN {
            -- Must run BEFORE conversation_characters is wiped below — a
            -- never-promoted NPC (origin='npc') dies with the conversation
            -- that spawned it; a promoted one (origin='gallery') survives.
            -- role IN ['npc', 'transient'] — NOT just 'npc': a candidate that
            -- crossed the two-pass debounce and got a full profile is
            -- role='npc', but most auto-detected speakers sit at
            -- role='transient' (their placeholder, registered the moment
            -- they were first detected) for a while, sometimes indefinitely
            -- if the story never brings them back for a second pass. Matching
            -- only 'npc' left every transient speaker behind as an invisible
            -- orphan character row whenever their conversation was deleted.
            DELETE FROM characters WHERE origin = 'npc' AND id INSIDE (
                SELECT VALUE character_id FROM conversation_characters
                WHERE conversation_id = $before.id AND role IN ['npc', 'transient']
            );
            DELETE FROM messages WHERE conversation_id = $before.id;
            DELETE FROM scenes WHERE conversation_id = $before.id;
            DELETE FROM scene_states WHERE conversation_id = $before.id;
            DELETE FROM conversation_characters WHERE conversation_id = $before.id;
            DELETE FROM memories WHERE conversation_id = $before.id;
            DELETE FROM character_states WHERE conversation_id = $before.id;
            DELETE FROM conversation_summaries WHERE conversation_id = $before.id;
            DELETE FROM message_embeddings WHERE conversation_id = $before.id;
            DELETE FROM npc_candidates WHERE conversation_id = $before.id;
            DELETE FROM npc_detection_state WHERE conversation_id = $before.id;
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:cascade_conv: {}", e)))?;

    db.query(
        "
        DEFINE EVENT IF NOT EXISTS cascade_memory_delete ON TABLE memories
            WHEN $event = 'DELETE' THEN {
            DELETE FROM memory_link WHERE in = $before.id;
            DELETE FROM memory_link WHERE linked_memory_id = $before.id;
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:cascade_mem: {}", e)))?;

    db.query(
        "
        DEFINE EVENT IF NOT EXISTS cascade_image_preset_delete ON TABLE image_presets
            WHEN $event = 'DELETE' THEN {
            UPDATE conversations SET image_preset_id = NONE WHERE image_preset_id = $before.id;
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:cascade_image_preset: {}", e)))?;

    db.query(
        "
        DEFINE EVENT IF NOT EXISTS cascade_persona_delete ON TABLE personas
            WHEN $event = 'DELETE' THEN {
            UPDATE conversations SET persona_id = NONE WHERE persona_id = $before.id;
        };
    ",
    )
    .await?
    .check()
    .map_err(|e| MythicError::DatabaseOp(format!("schema:cascade_persona: {}", e)))?;

    Ok(())
}
