// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns basic app information for the frontend. */
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	/**  Creates a new character from a Character Card V2 payload. */
	createCharacter: (name: string, data: JsonValue) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("create_character", { name, data })),
	/**  Retrieves a single character by ID. */
	getCharacter: (id: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("get_character", { id })),
	/**  Lists all characters, ordered by most recently updated. */
	listCharacters: () => typedError<Character_Serialize[], MythicError>(__TAURI_INVOKE("list_characters")),
	/**  Updates an existing character's data. */
	updateCharacter: (id: string, name: string | null, data: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null, avatarPath: string | null) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("update_character", { id, name, data, avatarPath })),
	/**  Deletes a character by ID. Cascades are handled by SurrealDB events. */
	deleteCharacter: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_character", { id })),
	/**
	 *  Returns the current emotional state for a character in a conversation.
	 *  Returns `None` if no state has been recorded yet (first turn).
	 */
	getCharacterState: (characterId: string, conversationId: string) => typedError<{
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
} | null, MythicError>(__TAURI_INVOKE("get_character_state", { characterId, conversationId })),
	/**
	 *  Upserts the emotional state for a character in a conversation.
	 *  All integer axes are clamped to [0, 100].
	 */
	upsertCharacterState: (characterId: string, conversationId: string, mood: number, trust: number, arousal: number, dominantEmotion: string, stateSummary: string) => typedError<CharacterState_Serialize, MythicError>(__TAURI_INVOKE("upsert_character_state", { characterId, conversationId, mood, trust, arousal, dominantEmotion, stateSummary })),
	/**  Creates a new conversation for a character. */
	createConversation: (characterId: string | null, title: string | null) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("create_conversation", { characterId, title })),
	/**  Retrieves a single conversation by ID. */
	getConversation: (id: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("get_conversation", { id })),
	/**  Lists conversations with pagination, ordered by most recently updated. */
	listConversations: (limit: number | null, offset: number | null) => typedError<Conversation_Serialize[], MythicError>(__TAURI_INVOKE("list_conversations", { limit, offset })),
	/**  Returns the total number of conversations (for pagination). */
	countConversations: () => typedError<number, MythicError>(__TAURI_INVOKE("count_conversations")),
	/**  Deletes a conversation and all its messages (cascade). */
	deleteConversation: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_conversation", { id })),
	/**
	 *  Retrieves all messages in a conversation, ordered chronologically.
	 *  Returns the linear message chain following the active branch.
	 */
	getConversationMessages: (conversationId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_conversation_messages", { conversationId })),
	/**  Updates the active message pointer for branch navigation. */
	setActiveMessage: (conversationId: string, messageId: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_active_message", { conversationId, messageId })),
	/**  Updates a conversation's title. */
	updateConversation: (id: string, title: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("update_conversation", { id, title })),
	/**  Updates the memory scope for a conversation. */
	setMemoryScope: (conversationId: string, scope: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_memory_scope", { conversationId, scope })),
	/**
	 *  Creates a new conversation that is a branch of an existing one.
	 * 
	 *  The new conversation contains a full copy of all messages up to and including
	 *  `branch_point_message_id`, preserving the parent→child chain with fresh IDs.
	 * 
	 *  All memories from the parent conversation are bulk-copied into the new conversation
	 *  using `copy` links, which render as dashed arrows in MemoryGraph/MemoryTimeline.
	 */
	branchConversation: (parentConversationId: string, branchPointMessageId: string, newTitle: string | null) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("branch_conversation", { parentConversationId, branchPointMessageId, newTitle })),
	/**
	 *  Searches message content using SurrealDB full-text search.
	 * 
	 *  Returns results with highlighted snippets, conversation titles,
	 *  and character names for display in the search overlay.
	 */
	searchMessages: (query: string, limit: number | null) => typedError<SearchResult_Serialize[], MythicError>(__TAURI_INVOKE("search_messages", { query, limit })),
	/**  Creates a new message in a conversation. */
	createMessage: (conversationId: string, role: string, content: string, parentId: string | null, metadata: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null) => typedError<Message_Serialize, MythicError>(__TAURI_INVOKE("create_message", { conversationId, role, content, parentId, metadata })),
	/**  Updates a message's content (for edits). */
	updateMessage: (id: string, content: string) => typedError<Message_Serialize, MythicError>(__TAURI_INVOKE("update_message", { id, content })),
	/**  Deletes a message by ID. */
	deleteMessage: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_message", { id })),
	/**
	 *  Walks the parent_id chain to reconstruct the linear message history
	 *  from root to the given message. Used for building the LLM prompt.
	 */
	getMessageBranch: (messageId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_message_branch", { messageId })),
	/**
	 *  Returns all sibling messages (messages sharing the same parent_id).
	 *  Used for branch navigation — shows alternates at the same conversation point.
	 */
	getMessageSiblings: (messageId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_message_siblings", { messageId })),
	/**  Creates a new provider configuration. */
	createProvider: (name: string, providerType: string, adapter: string, config: JsonValue, isDefault: boolean | null) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("create_provider", { name, providerType, adapter, config, isDefault })),
	/**  Retrieves a single provider by ID. */
	getProvider: (id: string) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("get_provider", { id })),
	/**  Lists all providers, optionally filtered by type. */
	listProviders: (providerType: string | null) => typedError<ProviderConfig_Serialize[], MythicError>(__TAURI_INVOKE("list_providers", { providerType })),
	/**  Updates an existing provider configuration. */
	updateProvider: (id: string, name: string | null, config: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("update_provider", { id, name, config })),
	/**  Deletes a provider configuration. */
	deleteProvider: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_provider", { id })),
	/**  Sets a provider as the default for its type. Unsets all others of the same type. */
	setDefaultProvider: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_default_provider", { id })),
	/**  Tests connectivity to a provider by attempting a health check. */
	testProviderConnection: (id: string) => typedError<boolean, MythicError>(__TAURI_INVOKE("test_provider_connection", { id })),
	/**
	 *  Lists available models from a provider's API.
	 *  Supports Ollama (/api/tags), OpenRouter (/api/v1/models), and OpenAI-compatible (/v1/models).
	 */
	listProviderModels: (id: string) => typedError<string[], MythicError>(__TAURI_INVOKE("list_provider_models", { id })),
	/**
	 *  Fetches models from ALL configured providers in parallel and merges them
	 *  with their enabled/disabled state from the `enabled_models` table.
	 * 
	 *  Per-provider fetches time out after 8 seconds. Partial results are returned
	 *  on timeout or network error rather than failing the whole call.
	 */
	listAllModels: () => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_all_models")),
	/**
	 *  Fetches **embedding** models from all configured providers in parallel.
	 * 
	 *  For OpenRouter: uses the dedicated `/api/v1/embeddings/models` endpoint.
	 *  For Ollama/LM Studio/OpenAI-compatible: fetches standard model lists and
	 *  filters for model IDs containing "embed".
	 */
	listEmbeddingModels: () => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_embedding_models")),
	/**
	 *  Toggles a model's enabled state in the `enabled_models` table.
	 *  Uses SurrealDB UPSERT for clean first-time toggling.
	 */
	toggleModelEnabled: (providerId: string, modelId: string, modelType: string, enabled: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_model_enabled", { providerId, modelId, modelType, enabled })),
	/**  Returns all enabled models (enabled=true only), enriched with provider name and adapter. */
	listEnabledModels: (providerId: string | null) => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_enabled_models", { providerId })),
	/**  Lists all lorebook entries for a character (plus global entries). */
	listLorebookEntries: (characterId: string) => typedError<LorebookEntry_Serialize[], MythicError>(__TAURI_INVOKE("list_lorebook_entries", { characterId })),
	/**  Creates a new lorebook entry. */
	createLorebookEntry: (characterId: string | null, name: string, keys: string[], content: string, alwaysActive: boolean) => typedError<LorebookEntry_Serialize, MythicError>(__TAURI_INVOKE("create_lorebook_entry", { characterId, name, keys, content, alwaysActive })),
	/**  Toggles a lorebook entry's enabled state. */
	toggleLorebookEntry: (id: string, enabled: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_lorebook_entry", { id, enabled })),
	/**  Deletes a lorebook entry. */
	deleteLorebookEntry: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_lorebook_entry", { id })),
	/**  Lists memories for a character and/or conversation. */
	listMemories: (characterId: string | null, conversationId: string | null) => typedError<Memory_Serialize[], MythicError>(__TAURI_INVOKE("list_memories", { characterId, conversationId })),
	/**  Creates a new memory entry. */
	createMemory: (characterId: string | null, conversationId: string | null, content: string, source: string | null) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("create_memory", { characterId, conversationId, content, source })),
	/**
	 *  Updates a memory's content and increments its version.
	 *  Also re-embeds the memory for semantic retrieval with the new content.
	 */
	updateMemory: (memoryId: string, content: string) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("update_memory", { memoryId, content })),
	/**
	 *  Sets a memory's importance tier (1-10), used to weight retrieval ranking
	 *  alongside semantic relevance and recency.
	 */
	setMemoryImportance: (memoryId: string, importance: number) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("set_memory_importance", { memoryId, importance })),
	/**  Deletes a memory entry. */
	deleteMemory: (memoryId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_memory", { memoryId })),
	/**
	 *  Promotes a conversation-level memory to character-level canon.
	 *  The memory becomes visible across all conversations with this character.
	 */
	promoteToCanon: (memoryId: string) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("promote_to_canon", { memoryId })),
	/**
	 *  Shares a memory to another conversation by creating a link.
	 * 
	 *  For 'copy' links: creates a duplicate memory in the target conversation.
	 *  For 'sync' links: just creates the link (no duplicate).
	 */
	shareMemory: (sourceMemoryId: string, targetConversationId: string, linkType: string | null, direction: string | null, syncMode: string | null) => typedError<MemoryLink_Serialize, MythicError>(__TAURI_INVOKE("share_memory", { sourceMemoryId, targetConversationId, linkType, direction, syncMode })),
	/**  Removes a sharing link between conversations. */
	unlinkMemory: (linkId: string) => typedError<null, MythicError>(__TAURI_INVOKE("unlink_memory", { linkId })),
	/**
	 *  Returns the full memory graph for a character — all memories, links,
	 *  and conversations, structured for the frontend graph canvas.
	 */
	getMemoryGraph: (characterId: string) => typedError<MemoryGraph_Serialize, MythicError>(__TAURI_INVOKE("get_memory_graph", { characterId })),
	/**
	 *  Generates a scene image from a prompt and saves it to the database + filesystem.
	 * 
	 *  This command:
	 *  1. Looks up the configured image provider
	 *  2. Calls generate_image with the provided prompt
	 *  3. Saves the resulting PNG to `scenes/{id}.png`
	 *  4. Creates a database record linking the scene to the conversation
	 */
	generateScene: (conversationId: string, messageId: string | null, prompt: string, negativePrompt: string | null, width: number | null, height: number | null) => typedError<Scene_Serialize, MythicError>(__TAURI_INVOKE("generate_scene", { conversationId, messageId, prompt, negativePrompt, width, height })),
	/**  Lists all scenes for a given conversation. */
	listScenes: (conversationId: string) => typedError<Scene_Serialize[], MythicError>(__TAURI_INVOKE("list_scenes", { conversationId })),
	/**  Deletes a scene and its media file. */
	deleteScene: (sceneId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_scene", { sceneId })),
	/**  Returns the absolute file path for a scene's media file. */
	getScenePath: (fileRelative: string) => typedError<string, MythicError>(__TAURI_INVOKE("get_scene_path", { fileRelative })),
	/**
	 *  Returns the current scene state for a conversation.
	 *  Returns `None` if no scene state has been established yet.
	 */
	getSceneState: (conversationId: string) => typedError<{
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at: string,
} | null, MythicError>(__TAURI_INVOKE("get_scene_state", { conversationId })),
	/**
	 *  Manually upserts the scene state for a conversation.
	 *  Used by the frontend for manual overrides.
	 */
	upsertSceneState: (conversationId: string, locationName: string | null, locationDescription: string | null, timePeriod: string | null, weather: string | null, charactersPresent: string[] | null, ambientDetails: string | null, sceneMood: string | null) => typedError<SceneState_Serialize, MythicError>(__TAURI_INVOKE("upsert_scene_state", { conversationId, locationName, locationDescription, timePeriod, weather, charactersPresent, ambientDetails, sceneMood })),
	/**  Deletes the scene state for a conversation. */
	deleteSceneState: (conversationId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_scene_state", { conversationId })),
	/**  Lists all characters in a conversation. */
	listConversationCharacters: (conversationId: string) => typedError<ConversationCharacter_Serialize[], MythicError>(__TAURI_INVOKE("list_conversation_characters", { conversationId })),
	/**  Adds a character to a conversation. */
	addConversationCharacter: (conversationId: string, characterId: string, characterName: string, role: string | null, talkativeness: number | null) => typedError<ConversationCharacter_Serialize, MythicError>(__TAURI_INVOKE("add_conversation_character", { conversationId, characterId, characterName, role, talkativeness })),
	/**  Removes a character from a conversation. */
	removeConversationCharacter: (conversationId: string, characterId: string) => typedError<null, MythicError>(__TAURI_INVOKE("remove_conversation_character", { conversationId, characterId })),
	/**  Updates a character's talkativeness in a conversation. */
	updateCharacterTalkativeness: (conversationId: string, characterId: string, talkativeness: number) => typedError<null, MythicError>(__TAURI_INVOKE("update_character_talkativeness", { conversationId, characterId, talkativeness })),
	/**  Toggles whether a character is active (unmuted) in a conversation. */
	toggleCharacterActive: (conversationId: string, characterId: string, isActive: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_character_active", { conversationId, characterId, isActive })),
	/**
	 *  Returns the current state of the vector embedding index.
	 * 
	 *  The frontend uses this to show how many messages are embedded,
	 *  which model was used, and whether a rebuild is needed.
	 */
	getEmbeddingIndexStatus: (conversationId: string | null, selectedModel: string | null) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("get_embedding_index_status", { conversationId, selectedModel })),
	/**
	 *  Rebuilds the embedding index by deleting existing embeddings and
	 *  re-embedding all user/assistant messages with the specified model.
	 * 
	 *  Returns the updated `EmbeddingIndexStatus` when done.
	 */
	rebuildEmbeddingIndex: (conversationId: string | null, embeddingModel: string) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("rebuild_embedding_index", { conversationId, embeddingModel })),
	/**
	 *  Finds messages that don't have embeddings yet and embeds them in batches.
	 *  This is a non-destructive catch-up — it only fills gaps without touching
	 *  existing embeddings. Designed to run on conversation load or periodically.
	 * 
	 *  Returns the updated `EmbeddingIndexStatus` when done.
	 */
	backfillMissingEmbeddings: (conversationId: string | null) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("backfill_missing_embeddings", { conversationId })),
	/**
	 *  Imports a character from a PNG file containing embedded Character Card V2 data.
	 * 
	 *  Flow:
	 *  1. User selects a PNG via the file dialog
	 *  2. Read the PNG bytes
	 *  3. Extract the "chara" tEXt chunk and decode base64
	 *  4. Parse as CharacterCardV2 JSON
	 *  5. Save the character to the database
	 *  6. Copy the PNG as the character's avatar
	 */
	importCharacterCard: (filePath: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("import_character_card", { filePath })),
	/**
	 *  Serves an avatar image from the app data directory.
	 *  Returns the absolute path to the avatar file for the frontend to load.
	 */
	getAvatarPath: (avatarRelative: string) => typedError<string, MythicError>(__TAURI_INVOKE("get_avatar_path", { avatarRelative })),
	/**
	 *  Sends a user message and streams the AI response back.
	 * 
	 *  This is the primary chat endpoint. It:
	 *  1. Saves the user message to the database
	 *  2. Builds the full prompt from character data + conversation history
	 *  3. Streams the response from the active LLM provider
	 *  4. Saves the completed AI response to the database
	 */
	sendMessage: (conversationId: string, content: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("send_message", { conversationId, content, model, systemPrompt, streaming, postHistoryInstructions })),
	/**
	 *  Retries a failed message by reusing the existing user message already in the DB.
	 *  Cleans up the empty/failed assistant placeholder from the previous attempt,
	 *  creates a fresh one, and re-triggers LLM generation. This avoids duplicating
	 *  the user message in both the UI and database.
	 */
	retryFailedMessage: (conversationId: string, userMessageId: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("retry_failed_message", { conversationId, userMessageId, model, systemPrompt, streaming, postHistoryInstructions })),
	/**
	 *  Regenerates the AI response for a given message by re-running generation
	 *  from the same parent point in the conversation tree.
	 */
	regenerateMessage: (conversationId: string, messageId: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("regenerate_message", { conversationId, messageId, model, systemPrompt, streaming, postHistoryInstructions })),
	/**
	 *  Stateless LLM generation — calls the configured provider without saving
	 *  anything to the database. Used by internal pipelines (memory extraction,
	 *  summarization) that need LLM inference without polluting conversations.
	 */
	generateRaw: (systemPrompt: string, userPrompt: string, model: string | null, maxTokens: number | null, temperature: number | null) => typedError<string, MythicError>(__TAURI_INVOKE("generate_raw", { systemPrompt, userPrompt, model, maxTokens, temperature })),
	/**
	 *  Returns context window statistics for a conversation.
	 *  Used by the frontend to display token usage and context budget info.
	 */
	getContextStats: (conversationId: string, messageId: string, systemPrompt: string | null, postHistoryInstructions: string | null) => typedError<ContextStats, MythicError>(__TAURI_INVOKE("get_context_stats", { conversationId, messageId, systemPrompt, postHistoryInstructions })),
	/**
	 *  Cancels the in-flight generation for a conversation, if any.
	 * 
	 *  Aborts the generation task and, for a streaming generation, persists
	 *  whatever content had already streamed so the response isn't lost just
	 *  because it was stopped early — a cancelled message is not the same as a
	 *  failed one. Emits a "cancelled" chat-stream event (not "done" or "error")
	 *  so the frontend can finalize the UI without triggering the auto-memory-
	 *  extraction/emotion-update pipelines that "done" runs, since those
	 *  shouldn't fire over content the user explicitly cut off.
	 * 
	 *  A no-op (not an error) if nothing is in flight for this conversation —
	 *  e.g. the user clicked Stop just as generation finished on its own.
	 */
	cancelGeneration: (conversationId: string) => typedError<null, MythicError>(__TAURI_INVOKE("cancel_generation", { conversationId })),
};

/* Types */
/**  Basic app metadata surfaced to the frontend (About screen, etc.). */
export type AppInfo = {
	name: string,
	version: string,
	description: string,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character = Character_Serialize | Character_Deserialize;

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState = CharacterState_Serialize | CharacterState_Deserialize;

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState_Deserialize = {
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
};

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState_Serialize = {
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character_Deserialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB */
	data: JsonValue,
	/**  Path to the character's avatar image file (relative to app data dir) */
	avatar_path: string | null,
	created_at?: string,
	updated_at?: string,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character_Serialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB */
	data: JsonValue,
	/**  Path to the character's avatar image file (relative to app data dir) */
	avatar_path: string | null,
	created_at: string,
	updated_at: string,
};

/**
 *  Statistics about the context window for observability.
 *  Returned alongside the prompt so callers can log/surface token usage.
 */
export type ContextStats = {
	/**  Total token budget for the context window. */
	total_budget: number,
	/**  Tokens used by fixed layers (system, character, lorebook, memories, emotion, PHI). */
	fixed_tokens: number,
	/**  Tokens used by conversation history (after sliding window). */
	history_tokens: number,
	/**  Tokens used by the rolling summary (0 if no summary yet). */
	summary_tokens: number,
	/**  Total messages in the full conversation branch. */
	total_messages: number,
	/**  Messages included in the sliding window. */
	included_messages: number,
	/**  Messages evicted (not sent to the LLM). */
	evicted_messages: number,
	/**  Tokens used by RAG-retrieved context (0 if RAG disabled or no results). */
	rag_tokens: number,
};

/**  A conversation session between the user and a character. */
export type Conversation = Conversation_Serialize | Conversation_Deserialize;

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter = ConversationCharacter_Serialize | ConversationCharacter_Deserialize;

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter_Deserialize = {
	id: string,
	conversation_id: string,
	character_id: string,
	/**  "primary" | "secondary" | "npc" */
	role: string,
	/**  0-100: how often the AI should include this character's response */
	talkativeness: number,
	/**  Whether the character is currently active in the scene (false = muted) */
	is_active: boolean,
	/**  Character name (denormalized for convenience in prompt building) */
	character_name?: string,
	created_at?: string,
};

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter_Serialize = {
	id: string,
	conversation_id: string,
	character_id: string,
	/**  "primary" | "secondary" | "npc" */
	role: string,
	/**  0-100: how often the AI should include this character's response */
	talkativeness: number,
	/**  Whether the character is currently active in the scene (false = muted) */
	is_active: boolean,
	/**  Character name (denormalized for convenience in prompt building) */
	character_name: string,
	created_at: string,
};

/**  A conversation session between the user and a character. */
export type Conversation_Deserialize = {
	id: string,
	title: string,
	/**  The character associated with this conversation */
	character_id: string | null,
	/**  ID of the active (latest) message in the current branch */
	active_message_id?: string | null,
	/**
	 *  Controls how auto-extracted memories are scoped:
	 *  - "character"    — shared across all conversations with this character (default)
	 *  - "conversation" — isolated to this specific conversation only
	 *  - "none"         — auto-save disabled for this conversation
	 */
	memory_scope?: string,
	shared_character_ids?: string | null,
	/**  If this conversation was forked from another, this points to the parent conversation. */
	parent_conversation_id?: string | null,
	/**  The exact message in the parent conversation where the fork happened. */
	branch_point_message_id?: string | null,
	created_at?: string,
	updated_at?: string,
};

/**  A conversation session between the user and a character. */
export type Conversation_Serialize = {
	id: string,
	title: string,
	/**  The character associated with this conversation */
	character_id: string | null,
	/**  ID of the active (latest) message in the current branch */
	active_message_id: string | null,
	/**
	 *  Controls how auto-extracted memories are scoped:
	 *  - "character"    — shared across all conversations with this character (default)
	 *  - "conversation" — isolated to this specific conversation only
	 *  - "none"         — auto-save disabled for this conversation
	 */
	memory_scope: string,
	shared_character_ids: string | null,
	/**  If this conversation was forked from another, this points to the parent conversation. */
	parent_conversation_id: string | null,
	/**  The exact message in the parent conversation where the fork happened. */
	branch_point_message_id: string | null,
	created_at: string,
	updated_at: string,
};

/**  Embedding index status for the frontend Memory settings. */
export type EmbeddingIndexStatus = {
	/**  Total messages across all conversations (or in a specific one) */
	total_messages: number,
	/**  Messages that have embeddings stored */
	embedded_messages: number,
	/**  The model name used for existing embeddings (None if no embeddings exist) */
	index_model: string | null,
	/**  Whether the index needs rebuilding (stored model != selected model) */
	needs_rebuild: boolean,
	/**  Percentage of messages embedded (0-100) */
	coverage_percent: number | null,
	/**  Dimension of existing embeddings (None if no embeddings exist) */
	index_dimension: number | null,
	/**  Dimension of the currently selected embedding model (from known dimensions map) */
	selected_dimension: number | null,
	/**  Whether dimensions mismatch between stored and selected model */
	dimension_mismatch: boolean,
};

/**
 *  A minimal recursive JSON type used purely as a `#[specta(type = JsonValue)]`
 *  override for `serde_json::Value` fields (arbitrary-shape blobs like
 *  character card data, provider config, message metadata).
 * 
 *  specta's own built-in `serde_json::Value` support (`legacy_impls.rs`,
 *  `serde_json` feature) registers it as an *inline* type whose `Array`/
 *  `Object` variants re-expand `Value::definition()` with no cycle-breaking —
 *  genuine infinite recursion on export, unrelated to any real data depth.
 *  A normally-derived enum like this one IS registered as a named/cached
 *  type by the derive macro, so the recursion terminates correctly. The
 *  actual Rust field stays `serde_json::Value`; this type only stands in for
 *  specta's reflection.
 * 
 *  `#[serde(untagged)]` is required so the exported TS type matches the real
 *  wire shape: `serde_json::Value` serializes as plain JSON (a bare number,
 *  string, object, etc.), not as a `{ "Bool": true }`-style tagged variant.
 *  Without it, specta falls back to externally-tagged rendering, producing a
 *  TS type that looks plausible but never matches the actual payload. The
 *  `Serialize`/`Deserialize` derives are never used to move real data (this
 *  type is never constructed) — they exist only so `#[serde(untagged)]` is a
 *  legal attribute here for specta's own (derive-independent) attribute
 *  parsing to read.
 */
export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry = LorebookEntry_Serialize | LorebookEntry_Deserialize;

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry_Deserialize = {
	id: string,
	/**  The character this entry belongs to (None = global lorebook) */
	character_id: string | null,
	/**
	 *  Trigger keywords — entry activates when any keyword is found in chat.
	 *  Stored as native array in SurrealDB.
	 */
	keys: string[],
	/**  The content to inject into the prompt when triggered */
	content: string,
	/**  Whether this entry is active */
	enabled: boolean,
	/**  If true, always injected regardless of keyword matches */
	always_active: boolean,
	/**  Priority level (higher = more important when context is limited) */
	priority: number,
	/**  Order relative to other entries in the prompt */
	insertion_order: number,
	/**  Optional display name for the entry */
	name: string | null,
};

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry_Serialize = {
	id: string,
	/**  The character this entry belongs to (None = global lorebook) */
	character_id: string | null,
	/**
	 *  Trigger keywords — entry activates when any keyword is found in chat.
	 *  Stored as native array in SurrealDB.
	 */
	keys: string[],
	/**  The content to inject into the prompt when triggered */
	content: string,
	/**  Whether this entry is active */
	enabled: boolean,
	/**  If true, always injected regardless of keyword matches */
	always_active: boolean,
	/**  Priority level (higher = more important when context is limited) */
	priority: number,
	/**  Order relative to other entries in the prompt */
	insertion_order: number,
	/**  Optional display name for the entry */
	name: string | null,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory = Memory_Serialize | Memory_Deserialize;

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph = MemoryGraph_Serialize | MemoryGraph_Deserialize;

/**  Minimal conversation info for graph rendering. */
export type MemoryGraphConversation = {
	id: string,
	title: string,
	character_id: string,
	memory_count: number,
	/**  If this conversation was branched from another, this is the parent's ID. */
	parent_conversation_id: string | null,
};

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph_Deserialize = {
	character_id: string,
	character_name: string,
	memories: Memory_Deserialize[],
	links: MemoryLink_Deserialize[],
	/**  Conversations that have memories for this character */
	conversations: MemoryGraphConversation[],
};

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph_Serialize = {
	character_id: string,
	character_name: string,
	memories: Memory_Serialize[],
	links: MemoryLink_Serialize[],
	/**  Conversations that have memories for this character */
	conversations: MemoryGraphConversation[],
};

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink = MemoryLink_Serialize | MemoryLink_Deserialize;

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink_Deserialize = {
	id: string,
	link_type: string,
	direction: string,
	sync_mode: string,
	linked_memory_id?: string | null,
	created_at?: string,
} & {
	in: string,
} & {
	out: string,
};

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink_Serialize = {
	id: string,
	source_memory_id: string,
	target_conversation_id: string,
	link_type: string,
	direction: string,
	sync_mode: string,
	linked_memory_id: string | null,
	created_at: string,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory_Deserialize = {
	id: string,
	character_id?: string | null,
	conversation_id?: string | null,
	content: string,
	source: string,
	/**  Parent memory this was forked/inherited from (None = root) */
	parent_id?: string | null,
	/**  Version counter — increments on each edit */
	version: number,
	/**  Whether this is a character-level "canon" memory (trunk of the tree) */
	is_canon: boolean,
	created_at?: string,
	/**
	 *  Manual importance tier (1-10, default 5/neutral) used to weight
	 *  retrieval ranking alongside semantic relevance and recency.
	 */
	importance?: number,
	/**
	 *  When this memory was last surfaced to the LLM via retrieval — `None`
	 *  if it has never been retrieved (including all rows predating this
	 *  field, which are absent from storage rather than defaulted).
	 */
	last_accessed?: string | null,
	/**  How many times this memory has been surfaced via retrieval. */
	access_count?: number,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory_Serialize = {
	id: string,
	character_id: string | null,
	conversation_id: string | null,
	content: string,
	source: string,
	/**  Parent memory this was forked/inherited from (None = root) */
	parent_id: string | null,
	/**  Version counter — increments on each edit */
	version: number,
	/**  Whether this is a character-level "canon" memory (trunk of the tree) */
	is_canon: boolean,
	created_at: string,
	/**
	 *  Manual importance tier (1-10, default 5/neutral) used to weight
	 *  retrieval ranking alongside semantic relevance and recency.
	 */
	importance: number,
	/**
	 *  When this memory was last surfaced to the LLM via retrieval — `None`
	 *  if it has never been retrieved (including all rows predating this
	 *  field, which are absent from storage rather than defaulted).
	 */
	last_accessed: string | null,
	/**  How many times this memory has been surfaced via retrieval. */
	access_count: number,
};

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message = Message_Serialize | Message_Deserialize;

/**  The role of a message sender in a conversation. */
export type MessageRole = 
/**  Message from the user */
"user" | 
/**  Message from the AI character */
"assistant" | 
/**  System-level instruction (not displayed to user) */
"system";

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message_Deserialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**
	 *  Parent message ID — enables conversation branching.
	 *  If None, this is a root message.
	 */
	parent_id?: string | null,
	/**  JSON metadata for attached images, generation params, etc. */
	metadata: JsonValue | null,
	/**
	 *  Character who sent this message (for multi-character conversations).
	 *  None for user messages and single-character conversations.
	 */
	character_id?: string | null,
	/**  Denormalized character name for display (avoids extra lookups). */
	character_name?: string | null,
	created_at?: string,
};

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message_Serialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**
	 *  Parent message ID — enables conversation branching.
	 *  If None, this is a root message.
	 */
	parent_id: string | null,
	/**  JSON metadata for attached images, generation params, etc. */
	metadata: JsonValue | null,
	/**
	 *  Character who sent this message (for multi-character conversations).
	 *  None for user messages and single-character conversations.
	 */
	character_id: string | null,
	/**  Denormalized character name for display (avoids extra lookups). */
	character_name: string | null,
	created_at: string,
};

/**  A single model entry returned by `list_all_models`. */
export type ModelEntry = {
	model_id: string,
	provider_id: string,
	provider_name: string,
	adapter: string,
	model_type: string,
	context_length: number | null,
	enabled: boolean,
	display_name: string | null,
	description: string | null,
	pricing_prompt: string | null,
	pricing_completion: string | null,
	is_free: boolean,
	max_completion_tokens: number | null,
	input_modalities: string[],
	output_modalities: string[],
	supports_tools: boolean,
	supports_vision: boolean,
	supports_reasoning: boolean,
	/**  Embedding vector dimensions (populated for embedding models) */
	embedding_dimensions: number | null,
	/**
	 *  True when this model is enabled locally but no longer appears in the
	 *  provider's live catalog (e.g. delisted upstream). Stale entries carry
	 *  no fetched metadata (pricing, context length, etc.) — just enough to
	 *  show the user what's enabled and let them turn it off.
	 */
	is_stale: boolean,
};

/**
 *  Mirrors the exact `{ error, message }` wire shape produced by
 *  `MythicError`'s custom `Serialize` impl above — exists solely so
 *  `MythicError` can implement `specta::Type` by delegating to it.
 * 
 *  Every Tauri command returns `Result<T, MythicError>`; specta's blanket
 *  impl for async function results requires the whole `Result<T, E>` to
 *  implement `Type`, which in turn requires *both* T and E to implement it.
 *  Without this, every async command fails to satisfy `FunctionResult` —
 *  a runtime-of-macro-expansion error, not something `cargo check` on the
 *  type alone would reveal, since compiling this file in isolation is fine.
 */
export type MythicError = {
	error: string,
	message: string,
};

/**  The specific adapter implementation for a provider. */
export type ProviderAdapter = 
/**  Local Ollama instance */
"ollama" | 
/**  OpenRouter API aggregator */
"open_router" | 
/**  Generic OpenAI-compatible API (works with LM Studio, KoboldCPP, vLLM, etc.) */
"open_ai_compatible" | 
/**  SiliconFlow API (LLM + Image + Video) */
"silicon_flow" | 
/**  Hugging Face Inference API */
"hugging_face" | 
/**  Local ComfyUI instance for image/video generation */
"comfy_ui" | 
/**  Anthropic API (Claude models) */
"anthropic" | 
/**  Google Gemini API */
"gemini" | 
/**  Cohere API (Command R+) */
"cohere" | 
/**  DeepSeek API */
"deep_seek" | 
/**  Groq API (fast inference) */
"groq" | 
/**  Perplexity API (search-augmented) */
"perplexity" | 
/**  xAI API (Grok models) */
"xai" | 
/**  Hyperbolic API */
"hyperbolic" | 
/**  Moonshot API (Kimi) */
"moonshot" | 
/**  Together API (open-source models) */
"together";

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig_Deserialize = {
	id: string,
	/**  Human-readable name (e.g., "My Local Ollama", "OpenRouter Free") */
	name: string,
	/**  What this provider does */
	provider_type: ProviderType,
	/**  Which adapter implementation to use */
	adapter: ProviderAdapter,
	/**
	 *  Adapter-specific configuration as native JSON.
	 * 
	 *  For Ollama: `{ "base_url": "http://localhost:11434" }`
	 *  For OpenRouter: `{ "api_key": "sk-...", "model": "meta-llama/llama-4-maverick" }`
	 *  For OpenAI-compat: `{ "base_url": "...", "api_key": "...", "model": "..." }`
	 *  For ComfyUI: `{ "base_url": "http://localhost:8188", "workflow": "..." }`
	 */
	config: JsonValue,
	/**  Whether this is the default provider for its type */
	is_default: boolean,
};

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig_Serialize = {
	id: string,
	/**  Human-readable name (e.g., "My Local Ollama", "OpenRouter Free") */
	name: string,
	/**  What this provider does */
	provider_type: ProviderType,
	/**  Which adapter implementation to use */
	adapter: ProviderAdapter,
	/**
	 *  Adapter-specific configuration as native JSON.
	 * 
	 *  For Ollama: `{ "base_url": "http://localhost:11434" }`
	 *  For OpenRouter: `{ "api_key": "sk-...", "model": "meta-llama/llama-4-maverick" }`
	 *  For OpenAI-compat: `{ "base_url": "...", "api_key": "...", "model": "..." }`
	 *  For ComfyUI: `{ "base_url": "http://localhost:8188", "workflow": "..." }`
	 */
	config: JsonValue,
	/**  Whether this is the default provider for its type */
	is_default: boolean,
};

/**  The type of AI capability a provider offers. */
export type ProviderType = 
/**  Text generation / chat completion */
"llm" | 
/**  Image generation */
"image" | 
/**  Video generation */
"video";

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene = Scene_Serialize | Scene_Deserialize;

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState = SceneState_Serialize | SceneState_Deserialize;

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState_Deserialize = {
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present?: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at?: string,
};

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState_Serialize = {
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at: string,
};

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene_Deserialize = {
	id: string,
	conversation_id: string,
	message_id: string | null,
	media_type: string,
	prompt: string,
	file_path: string,
	caption: string | null,
	metadata: JsonValue | null,
	created_at?: string,
};

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene_Serialize = {
	id: string,
	conversation_id: string,
	message_id: string | null,
	media_type: string,
	prompt: string,
	file_path: string,
	caption: string | null,
	metadata: JsonValue | null,
	created_at: string,
};

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult = SearchResult_Serialize | SearchResult_Deserialize;

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult_Deserialize = {
	message_id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**  Snippet with `<mark>` tags around matched terms */
	snippet: string,
	conversation_title: string,
	character_name: string | null,
	created_at?: string,
};

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult_Serialize = {
	message_id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**  Snippet with `<mark>` tags around matched terms */
	snippet: string,
	conversation_title: string,
	character_name: string | null,
	created_at: string,
};

/**
 *  The IDs of the user/assistant message pair created by `send_message`,
 *  `retry_failed_message`, or `regenerate_message` — the frontend uses
 *  these to attach the streamed response to the right message bubbles.
 */
export type SendMessageResult = {
	user_message_id: string,
	assistant_message_id: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

