// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns basic app information for the frontend. */
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	/**  Creates a new character from a Character Card V2 payload. */
	createCharacter: (name: string, data: JsonValue) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("create_character", { name, data })),
	/**  Retrieves a single character by ID. */
	getCharacter: (id: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("get_character", { id })),
	/**  Lists all characters, ordered by most recently updated. */
	listCharacters: () => typedError<Character_Serialize[], MythicError>(__TAURI_INVOKE("list_characters")),
	/**  Updates an existing character's data. */
	updateCharacter: (id: string, name: string | null, data: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null, avatarPath: string | null) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("update_character", { id, name, data, avatarPath })),
	/**
	 *  Permanently deletes a character by ID. Cascades are handled by SurrealDB
	 *  events. Only the Trash view should call this — normal deletion from
	 *  Gallery should call `trash_character` instead.
	 */
	deleteCharacter: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_character", { id })),
	/**  Moves a character to Trash (soft delete) — reversible via `restore_character`. */
	trashCharacter: (id: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("trash_character", { id })),
	/**  Restores a trashed character. */
	restoreCharacter: (id: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("restore_character", { id })),
	/**
	 *  Sets a character's portrait directly from a user-picked image file,
	 *  bypassing AI generation entirely — the "Upload Portrait" counterpart to
	 *  `generate_npc_portrait`. Always marks the result "approved" (a manually
	 *  chosen image needs no review gate). Copies the file into the app data
	 *  dir's `portraits/` folder, same location and naming (`{character_id}.png`)
	 *  AI-generated portraits use, so both paths are interchangeable afterward.
	 */
	uploadCharacterAvatar: (characterId: string, filePath: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("upload_character_avatar", { characterId, filePath })),
	/**
	 *  Returns the current emotional state for a character in a conversation.
	 *  Returns `None` if no state has been recorded yet (first turn).
	 */
	getCharacterState: (characterId: string, conversationId: string) => typedError<{
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
} | null, MythicError>(__TAURI_INVOKE("get_character_state", { characterId, conversationId })),
	/**
	 *  Upserts the emotional state for a character in a conversation.
	 *  All integer axes are clamped to [0, 100].
	 */
	upsertCharacterState: (characterId: string, conversationId: string, mood: number, trust: number, arousal: number, dominantEmotion: string, stateSummary: string) => typedError<CharacterState_Serialize, MythicError>(__TAURI_INVOKE("upsert_character_state", { characterId, conversationId, mood, trust, arousal, dominantEmotion, stateSummary })),
	/**
	 *  Freezes an emotional-state snapshot (one entry per character, keyed by
	 *  character id) onto a specific message's metadata, so its EmotionHUD pill
	 *  keeps showing what each character felt *at that point in the story*
	 *  instead of whatever `character_states` holds right now. `states` is
	 *  passed through as raw JSON rather than a typed map — the backend never
	 *  reads its shape, only stores and returns it verbatim to the frontend.
	 *  Uses `DynamicJson`, not a bare `serde_json::Value` param — see its doc
	 *  comment in `models::mod` for why (the same infinite-recursion crash
	 *  `JsonValue` was built to avoid).
	 */
	setMessageEmotionalSnapshot: (messageId: string, states: JsonValue) => typedError<null, MythicError>(__TAURI_INVOKE("set_message_emotional_snapshot", { messageId, states })),
	/**  Creates a new conversation for a character. */
	createConversation: (characterId: string | null, title: string | null, personaId: string | null) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("create_conversation", { characterId, title, personaId })),
	/**  Retrieves a single conversation by ID. */
	getConversation: (id: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("get_conversation", { id })),
	/**  Lists conversations with pagination, ordered by most recently updated. */
	listConversations: (limit: number | null, offset: number | null) => typedError<Conversation_Serialize[], MythicError>(__TAURI_INVOKE("list_conversations", { limit, offset })),
	/**  Returns the total number of conversations (for pagination). */
	countConversations: () => typedError<number, MythicError>(__TAURI_INVOKE("count_conversations")),
	/**
	 *  Permanently deletes a conversation and all its messages (cascade). Only
	 *  the Trash view should call this — normal deletion from the chat list
	 *  should call `trash_conversation` instead.
	 */
	deleteConversation: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_conversation", { id })),
	/**
	 *  Moves a conversation to Trash (soft delete) — reversible via
	 *  `restore_conversation`. Instant and durable the moment it returns, unlike
	 *  the old client-side undo-window that silently lost the delete if the app
	 *  reloaded before its timer fired.
	 */
	trashConversation: (id: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("trash_conversation", { id })),
	/**  Restores a trashed conversation. */
	restoreConversation: (id: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("restore_conversation", { id })),
	/**
	 *  Retrieves all messages in a conversation, ordered chronologically.
	 *  Returns the linear message chain following the active branch.
	 */
	getConversationMessages: (conversationId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_conversation_messages", { conversationId })),
	/**  Updates the active message pointer for branch navigation. */
	setActiveMessage: (conversationId: string, messageId: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_active_message", { conversationId, messageId })),
	/**  Updates a conversation's title. */
	updateConversation: (id: string, title: string) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("update_conversation", { id, title })),
	/**  Updates the memory scope for a conversation. */
	setMemoryScope: (conversationId: string, scope: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_memory_scope", { conversationId, scope })),
	/**
	 *  Creates a new conversation that is a branch of an existing one.
	 * 
	 *  The new conversation contains a full copy of all messages up to and including
	 *  `branch_point_message_id`, preserving the parent→child chain with fresh IDs.
	 * 
	 *  All memories from the parent conversation are bulk-copied into the new conversation
	 *  using `copy` links, which render as dashed arrows in MemoryGraph/MemoryTimeline.
	 */
	branchConversation: (parentConversationId: string, branchPointMessageId: string, newTitle: string | null) => typedError<Conversation_Serialize, MythicError>(__TAURI_INVOKE("branch_conversation", { parentConversationId, branchPointMessageId, newTitle })),
	/**
	 *  Searches message content using SurrealDB full-text search.
	 * 
	 *  Returns results with highlighted snippets, conversation titles,
	 *  and character names for display in the search overlay.
	 */
	searchMessages: (query: string, limit: number | null) => typedError<SearchResult_Serialize[], MythicError>(__TAURI_INVOKE("search_messages", { query, limit })),
	/**  Creates a new message in a conversation. */
	createMessage: (conversationId: string, role: string, content: string, parentId: string | null, metadata: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null) => typedError<Message_Serialize, MythicError>(__TAURI_INVOKE("create_message", { conversationId, role, content, parentId, metadata })),
	/**  Updates a message's content (for edits). */
	updateMessage: (id: string, content: string) => typedError<Message_Serialize, MythicError>(__TAURI_INVOKE("update_message", { id, content })),
	/**  Deletes a message by ID. */
	deleteMessage: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_message", { id })),
	/**
	 *  Walks the parent_id chain to reconstruct the linear message history
	 *  from root to the given message. Used for building the LLM prompt.
	 */
	getMessageBranch: (messageId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_message_branch", { messageId })),
	/**
	 *  Returns all sibling messages (messages sharing the same parent_id).
	 *  Used for branch navigation — shows alternates at the same conversation point.
	 */
	getMessageSiblings: (messageId: string) => typedError<Message_Serialize[], MythicError>(__TAURI_INVOKE("get_message_siblings", { messageId })),
	/**
	 *  Creates a new provider configuration.
	 *  Creates a new provider configuration.
	 */
	createProvider: (name: string, providerType: string, adapter: string, config: JsonValue, isDefault: boolean | null) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("create_provider", { name, providerType, adapter, config, isDefault })),
	/**  Retrieves a single provider by ID. */
	getProvider: (id: string) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("get_provider", { id })),
	/**  Lists all providers, optionally filtered by type. */
	listProviders: (providerType: string | null) => typedError<ProviderConfig_Serialize[], MythicError>(__TAURI_INVOKE("list_providers", { providerType })),
	/**  Updates an existing provider configuration. */
	updateProvider: (id: string, name: string | null, config: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null) => typedError<ProviderConfig_Serialize, MythicError>(__TAURI_INVOKE("update_provider", { id, name, config })),
	/**  Deletes a provider configuration. */
	deleteProvider: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_provider", { id })),
	/**  Sets a provider as the default for its type. Unsets all others of the same type. */
	setDefaultProvider: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_default_provider", { id })),
	testProviderConnection: (id: string) => typedError<ConnectionTestResult, MythicError>(__TAURI_INVOKE("test_provider_connection", { id })),
	/**
	 *  Lists available models from a provider's API.
	 *  Supports Ollama (/api/tags), OpenRouter (/api/v1/models), and OpenAI-compatible (/v1/models).
	 */
	listProviderModels: (id: string) => typedError<string[], MythicError>(__TAURI_INVOKE("list_provider_models", { id })),
	/**
	 *  Fetches models from ALL configured providers in parallel and merges them
	 *  with their enabled/disabled state from the `enabled_models` table.
	 * 
	 *  Per-provider fetches time out after 8 seconds. Partial results are returned
	 *  on timeout or network error rather than failing the whole call.
	 */
	listAllModels: () => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_all_models")),
	/**
	 *  Fetches **embedding** models from all configured providers in parallel.
	 * 
	 *  For OpenRouter: uses the dedicated `/api/v1/embeddings/models` endpoint.
	 *  For Ollama/LM Studio/OpenAI-compatible: fetches standard model lists and
	 *  filters for model IDs containing "embed".
	 */
	listEmbeddingModels: () => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_embedding_models")),
	/**
	 *  Toggles a model's enabled state in the `enabled_models` table.
	 *  Uses SurrealDB UPSERT for clean first-time toggling.
	 */
	toggleModelEnabled: (providerId: string, modelId: string, modelType: string, enabled: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_model_enabled", { providerId, modelId, modelType, enabled })),
	/**  Returns all enabled models (enabled=true only), enriched with provider name and adapter. */
	listEnabledModels: (providerId: string | null) => typedError<ModelEntry[], MythicError>(__TAURI_INVOKE("list_enabled_models", { providerId })),
	/**  Lists all lorebook entries for a character (plus global entries). */
	listLorebookEntries: (characterId: string) => typedError<LorebookEntry_Serialize[], MythicError>(__TAURI_INVOKE("list_lorebook_entries", { characterId })),
	/**  Creates a new lorebook entry. */
	createLorebookEntry: (characterId: string | null, name: string, keys: string[], content: string, alwaysActive: boolean) => typedError<LorebookEntry_Serialize, MythicError>(__TAURI_INVOKE("create_lorebook_entry", { characterId, name, keys, content, alwaysActive })),
	/**  Toggles a lorebook entry's enabled state. */
	toggleLorebookEntry: (id: string, enabled: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_lorebook_entry", { id, enabled })),
	/**  Deletes a lorebook entry. */
	deleteLorebookEntry: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_lorebook_entry", { id })),
	/**
	 *  Updates a lorebook entry's editable fields — previously entries could
	 *  only be toggled on/off or deleted, never actually edited after creation.
	 */
	updateLorebookEntry: (id: string, name: string, keys: string[], content: string, alwaysActive: boolean, priority: number, insertionOrder: number) => typedError<LorebookEntry_Serialize, MythicError>(__TAURI_INVOKE("update_lorebook_entry", { id, name, keys, content, alwaysActive, priority, insertionOrder })),
	/**
	 *  Imports a character's embedded Character Card V2 `character_book` (if
	 *  any) as real, persisted lorebook entries. PNG import already does this
	 *  automatically now — this manual trigger exists for characters that were
	 *  imported before that existed, whose card-embedded lorebook the UI could
	 *  only ever *display*, never actually use during chat generation.
	 * 
	 *  Returns an empty list (not an error) if the character has no embedded
	 *  character_book, or it has zero entries.
	 */
	importCharacterBookEntries: (characterId: string) => typedError<LorebookEntry_Serialize[], MythicError>(__TAURI_INVOKE("import_character_book_entries", { characterId })),
	/**
	 *  Generates new lorebook entries for a character via the LLM — the
	 *  "Generate from Story" action. Grounds the generation in the character's
	 *  profile, canon/conversation facts, and recent dialogue (same context
	 *  `refresh_character_profile` uses), and tells the model which entries
	 *  already exist so it doesn't produce near-duplicates on a re-run.
	 *  Newly generated entries are persisted immediately, same as a manual add.
	 */
	generateCharacterLorebook: (characterId: string, conversationId: string) => typedError<LorebookEntry_Serialize[], MythicError>(__TAURI_INVOKE("generate_character_lorebook", { characterId, conversationId })),
	/**  Lists memories for a character and/or conversation. */
	listMemories: (characterId: string | null, conversationId: string | null) => typedError<Memory_Serialize[], MythicError>(__TAURI_INVOKE("list_memories", { characterId, conversationId })),
	/**  Creates a new memory entry. */
	createMemory: (characterId: string | null, conversationId: string | null, content: string, source: string | null) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("create_memory", { characterId, conversationId, content, source })),
	/**
	 *  Updates a memory's content and increments its version.
	 *  Also re-embeds the memory for semantic retrieval with the new content.
	 */
	updateMemory: (memoryId: string, content: string) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("update_memory", { memoryId, content })),
	/**
	 *  Sets a memory's importance tier (1-10), used to weight retrieval ranking
	 *  alongside semantic relevance and recency.
	 */
	setMemoryImportance: (memoryId: string, importance: number) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("set_memory_importance", { memoryId, importance })),
	/**  Deletes a memory entry. */
	deleteMemory: (memoryId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_memory", { memoryId })),
	/**
	 *  Promotes a conversation-level memory to character-level canon.
	 *  The memory becomes visible across all conversations with this character.
	 */
	promoteToCanon: (memoryId: string) => typedError<Memory_Serialize, MythicError>(__TAURI_INVOKE("promote_to_canon", { memoryId })),
	/**
	 *  Shares a memory to another conversation by creating a link.
	 * 
	 *  For 'copy' links: creates a duplicate memory in the target conversation.
	 *  For 'sync' links: just creates the link (no duplicate).
	 */
	shareMemory: (sourceMemoryId: string, targetConversationId: string, linkType: string | null, direction: string | null, syncMode: string | null) => typedError<MemoryLink_Serialize, MythicError>(__TAURI_INVOKE("share_memory", { sourceMemoryId, targetConversationId, linkType, direction, syncMode })),
	/**  Removes a sharing link between conversations. */
	unlinkMemory: (linkId: string) => typedError<null, MythicError>(__TAURI_INVOKE("unlink_memory", { linkId })),
	/**
	 *  Returns the full memory graph for a character — all memories, links,
	 *  and conversations, structured for the frontend graph canvas.
	 */
	getMemoryGraph: (characterId: string) => typedError<MemoryGraph_Serialize, MythicError>(__TAURI_INVOKE("get_memory_graph", { characterId })),
	/**
	 *  Generates a scene image from a prompt and saves it to the database + filesystem.
	 * 
	 *  This command:
	 *  1. Looks up the configured image provider
	 *  2. Calls generate_image with the provided prompt
	 *  3. Saves the resulting PNG to `scenes/{id}.png`
	 *  4. Creates a database record linking the scene to the conversation
	 */
	generateScene: (conversationId: string, messageId: string | null, prompt: string, options: GenerateSceneOptions) => typedError<Scene_Serialize, MythicError>(__TAURI_INVOKE("generate_scene", { conversationId, messageId, prompt, options })),
	/**
	 *  Generates a scene video from a prompt and saves it to the database +
	 *  filesystem — same shape as `generate_scene`, but for the video pipeline.
	 *  Unlike image generation, there's no generic/placeholder fallback: video
	 *  generation currently only exists via WanGP, so anything else (including
	 *  no video provider configured at all) is a clear, immediate error rather
	 *  than a silent placeholder (a placeholder *video* doesn't make sense).
	 */
	generateVideoScene: (conversationId: string, messageId: string | null, prompt: string, options: GenerateVideoOptions) => typedError<Scene_Serialize, MythicError>(__TAURI_INVOKE("generate_video_scene", { conversationId, messageId, prompt, options })),
	/**
	 *  Lists everyone available as a portrait-reference source for this
	 *  conversation's scene generation — the single source of truth the
	 *  frontend's cast-portrait picker uses, instead of re-deriving it from
	 *  several different props/stores that don't all carry raw avatar paths.
	 */
	listSceneCastMembers: (conversationId: string) => typedError<SceneCastMember[], MythicError>(__TAURI_INVOKE("list_scene_cast_members", { conversationId })),
	/**
	 *  Signals a running scene generation for this conversation to stop — the
	 *  poll loop notices within one tick (up to `AI_HORDE_POLL_INTERVAL`) and
	 *  issues a best-effort cancel to AI Horde before returning an error.
	 *  A no-op if nothing is currently generating for this conversation.
	 */
	cancelSceneGeneration: (conversationId: string) => typedError<null, MythicError>(__TAURI_INVOKE("cancel_scene_generation", { conversationId })),
	/**  Lists all scenes for a given conversation. */
	listScenes: (conversationId: string) => typedError<Scene_Serialize[], MythicError>(__TAURI_INVOKE("list_scenes", { conversationId })),
	/**  Deletes a scene and its media file. */
	deleteScene: (sceneId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_scene", { sceneId })),
	/**  Returns the absolute file path for a scene's media file. */
	getScenePath: (fileRelative: string) => typedError<string, MythicError>(__TAURI_INVOKE("get_scene_path", { fileRelative })),
	/**
	 *  Returns the current scene state for a conversation.
	 *  Returns `None` if no scene state has been established yet.
	 */
	getSceneState: (conversationId: string) => typedError<{
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at: string,
} | null, MythicError>(__TAURI_INVOKE("get_scene_state", { conversationId })),
	/**
	 *  Manually upserts the scene state for a conversation.
	 *  Used by the frontend for manual overrides.
	 */
	upsertSceneState: (conversationId: string, locationName: string | null, locationDescription: string | null, timePeriod: string | null, weather: string | null, charactersPresent: string[] | null, ambientDetails: string | null, sceneMood: string | null) => typedError<SceneState_Serialize, MythicError>(__TAURI_INVOKE("upsert_scene_state", { conversationId, locationName, locationDescription, timePeriod, weather, charactersPresent, ambientDetails, sceneMood })),
	/**  Deletes the scene state for a conversation. */
	deleteSceneState: (conversationId: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_scene_state", { conversationId })),
	listImagePresets: () => typedError<ImagePreset_Serialize[], MythicError>(__TAURI_INVOKE("list_image_presets")),
	createImagePreset: (name: string, fields: CreateImagePresetFields) => typedError<ImagePreset_Serialize, MythicError>(__TAURI_INVOKE("create_image_preset", { name, fields })),
	updateImagePreset: (id: string, fields: UpdateImagePresetFields) => typedError<ImagePreset_Serialize, MythicError>(__TAURI_INVOKE("update_image_preset", { id, fields })),
	deleteImagePreset: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_image_preset", { id })),
	setDefaultImagePreset: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("set_default_image_preset", { id })),
	/**
	 *  Sets (or clears, passing `null`) this conversation's chosen
	 *  image-generation preset.
	 */
	setConversationImagePreset: (conversationId: string, presetId: string | null) => typedError<null, MythicError>(__TAURI_INVOKE("set_conversation_image_preset", { conversationId, presetId })),
	/**  Lists all characters in a conversation. */
	listConversationCharacters: (conversationId: string) => typedError<ConversationCharacter_Serialize[], MythicError>(__TAURI_INVOKE("list_conversation_characters", { conversationId })),
	/**  Adds a character to a conversation. */
	addConversationCharacter: (conversationId: string, characterId: string, characterName: string, role: string | null, talkativeness: number | null) => typedError<ConversationCharacter_Serialize, MythicError>(__TAURI_INVOKE("add_conversation_character", { conversationId, characterId, characterName, role, talkativeness })),
	/**  Removes a character from a conversation. */
	removeConversationCharacter: (conversationId: string, characterId: string) => typedError<null, MythicError>(__TAURI_INVOKE("remove_conversation_character", { conversationId, characterId })),
	/**  Updates a character's talkativeness in a conversation. */
	updateCharacterTalkativeness: (conversationId: string, characterId: string, talkativeness: number) => typedError<null, MythicError>(__TAURI_INVOKE("update_character_talkativeness", { conversationId, characterId, talkativeness })),
	/**  Toggles whether a character is active (unmuted) in a conversation. */
	toggleCharacterActive: (conversationId: string, characterId: string, isActive: boolean) => typedError<null, MythicError>(__TAURI_INVOKE("toggle_character_active", { conversationId, characterId, isActive })),
	/**
	 *  Returns the current state of the vector embedding index.
	 * 
	 *  The frontend uses this to show how many messages are embedded,
	 *  which model was used, and whether a rebuild is needed.
	 */
	getEmbeddingIndexStatus: (conversationId: string | null, selectedModel: string | null) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("get_embedding_index_status", { conversationId, selectedModel })),
	/**
	 *  Rebuilds the embedding index by deleting existing embeddings and
	 *  re-embedding all user/assistant messages with the specified model.
	 * 
	 *  Returns the updated `EmbeddingIndexStatus` when done.
	 */
	rebuildEmbeddingIndex: (conversationId: string | null, embeddingModel: string) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("rebuild_embedding_index", { conversationId, embeddingModel })),
	/**
	 *  Finds messages that don't have embeddings yet and embeds them in batches.
	 *  This is a non-destructive catch-up — it only fills gaps without touching
	 *  existing embeddings. Designed to run on conversation load or periodically.
	 * 
	 *  Returns the updated `EmbeddingIndexStatus` when done.
	 */
	backfillMissingEmbeddings: (conversationId: string | null) => typedError<EmbeddingIndexStatus, MythicError>(__TAURI_INVOKE("backfill_missing_embeddings", { conversationId })),
	/**
	 *  Imports a character from a PNG file containing embedded Character Card V2 data.
	 * 
	 *  Flow:
	 *  1. User selects a PNG via the file dialog
	 *  2. Read the PNG bytes
	 *  3. Extract the "chara" tEXt chunk and decode base64
	 *  4. Parse as CharacterCardV2 JSON
	 *  5. Save the character to the database
	 *  6. Copy the PNG as the character's avatar
	 */
	importCharacterCard: (filePath: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("import_character_card", { filePath })),
	/**
	 *  Serves an avatar image from the app data directory.
	 *  Returns the absolute path to the avatar file for the frontend to load.
	 */
	getAvatarPath: (avatarRelative: string) => typedError<string, MythicError>(__TAURI_INVOKE("get_avatar_path", { avatarRelative })),
	/**
	 *  Sends a user message and streams the AI response back.
	 * 
	 *  This is the primary chat endpoint. It:
	 *  1. Saves the user message to the database
	 *  2. Builds the full prompt from character data + conversation history
	 *  3. Streams the response from the active LLM provider
	 *  4. Saves the completed AI response to the database
	 */
	sendMessage: (conversationId: string, content: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null, attachments: MessageAttachment[] | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("send_message", { conversationId, content, model, systemPrompt, streaming, postHistoryInstructions, attachments })),
	/**
	 *  Copies a user-picked image file (an absolute path from the frontend's
	 *  file dialog) into `app_data_dir/attachments/`, so it can be attached to
	 *  a chat message and later resolved via `crate::error::resolve_within`.
	 * 
	 *  Unlike `upload_character_avatar`, this preserves the source file's real
	 *  extension instead of hardcoding `.png` — the extension is how
	 *  `mime_type_for_extension` (and, on replay, `load_message_images`) knows
	 *  what MIME type to hand the provider.
	 */
	uploadMessageAttachment: (filePath: string) => typedError<MessageAttachment, MythicError>(__TAURI_INVOKE("upload_message_attachment", { filePath })),
	/**
	 *  Same as `upload_message_attachment`, but for an image pasted directly
	 *  from the clipboard (e.g. a screenshot) — there's no source file on disk
	 *  to read, just raw bytes and the clipboard blob's MIME type from the
	 *  frontend's `paste` event.
	 */
	uploadMessageAttachmentBytes: (bytes: number[], extension: string) => typedError<MessageAttachment, MythicError>(__TAURI_INVOKE("upload_message_attachment_bytes", { bytes, extension })),
	/**
	 *  Retries a failed message by reusing the existing user message already in the DB.
	 *  Cleans up the empty/failed assistant placeholder from the previous attempt,
	 *  creates a fresh one, and re-triggers LLM generation. This avoids duplicating
	 *  the user message in both the UI and database.
	 */
	retryFailedMessage: (conversationId: string, userMessageId: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("retry_failed_message", { conversationId, userMessageId, model, systemPrompt, streaming, postHistoryInstructions })),
	/**
	 *  Regenerates the AI response for a given message by re-running generation
	 *  from the same parent point in the conversation tree.
	 */
	regenerateMessage: (conversationId: string, messageId: string, model: string | null, systemPrompt: string | null, streaming: boolean | null, postHistoryInstructions: string | null) => typedError<SendMessageResult, MythicError>(__TAURI_INVOKE("regenerate_message", { conversationId, messageId, model, systemPrompt, streaming, postHistoryInstructions })),
	/**
	 *  Stateless LLM generation — calls the configured provider without saving
	 *  anything to the database. Used by internal pipelines (memory extraction,
	 *  summarization) that need LLM inference without polluting conversations.
	 */
	generateRaw: (systemPrompt: string, userPrompt: string, model: string | null, maxTokens: number | null, temperature: number | null) => typedError<string, MythicError>(__TAURI_INVOKE("generate_raw", { systemPrompt, userPrompt, model, maxTokens, temperature })),
	/**
	 *  Returns context window statistics for a conversation.
	 *  Used by the frontend to display token usage and context budget info.
	 */
	getContextStats: (conversationId: string, messageId: string, systemPrompt: string | null, postHistoryInstructions: string | null) => typedError<ContextStats, MythicError>(__TAURI_INVOKE("get_context_stats", { conversationId, messageId, systemPrompt, postHistoryInstructions })),
	/**
	 *  Cancels the in-flight generation for a conversation, if any.
	 * 
	 *  Aborts the generation task and, for a streaming generation, persists
	 *  whatever content had already streamed so the response isn't lost just
	 *  because it was stopped early — a cancelled message is not the same as a
	 *  failed one. Emits a "cancelled" chat-stream event (not "done" or "error")
	 *  so the frontend can finalize the UI without triggering the auto-memory-
	 *  extraction/emotion-update pipelines that "done" runs, since those
	 *  shouldn't fire over content the user explicitly cut off.
	 * 
	 *  A no-op (not an error) if nothing is in flight for this conversation —
	 *  e.g. the user clicked Stop just as generation finished on its own.
	 */
	cancelGeneration: (conversationId: string) => typedError<null, MythicError>(__TAURI_INVOKE("cancel_generation", { conversationId })),
	/**
	 *  Kicks off scene-state extraction for a message that never went through
	 *  the normal streaming pipeline — currently just the character's greeting.
	 *  Fire-and-forget: returns as soon as the background task is spawned.
	 */
	extractInitialScene: (conversationId: string, text: string) => typedError<null, MythicError>(__TAURI_INVOKE("extract_initial_scene", { conversationId, text })),
	/**
	 *  Lists the auto-detected cast currently in a conversation — both
	 *  `role = 'transient'` (just spoke for the first time, not yet confirmed
	 *  significant) and `role = 'npc'` (crossed the two-pass debounce and got a
	 *  real profile) members, plus already-promoted-to-gallery ones, since
	 *  promotion only changes `origin`, not cast membership. Transients are
	 *  included (not just 'npc') so a character who's clearly speaking and
	 *  developing a real identity doesn't just vanish from this panel while
	 *  waiting on the background debounce — the frontend badges them as
	 *  "Unconfirmed" rather than hiding them outright.
	 */
	listConversationNpcs: (conversationId: string) => typedError<Character_Serialize[], MythicError>(__TAURI_INVOKE("list_conversation_npcs", { conversationId })),
	/**
	 *  Promotes an auto-generated NPC into a real, standalone Gallery character
	 *  (`origin: 'npc' -> 'gallery'`). No cast/memory data moves — the NPC's
	 *  memories were already keyed by its own real `character_id` from creation,
	 *  and it keeps its existing `conversation_characters` row (still shows in
	 *  this conversation's cast) while now also being independently listable
	 *  and startable as a solo chat from the Gallery.
	 */
	promoteNpcToGallery: (characterId: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("promote_npc_to_gallery", { characterId })),
	/**
	 *  Manually promotes an auto-detected NPC from `role: 'transient'`
	 *  ("Unconfirmed" in the UI) straight to `role: 'npc'`, skipping the
	 *  automatic two-pass detector debounce (`pipeline::run_npc_detection`).
	 *  That debounce is entirely invisible to the user — a character can speak
	 *  repeatedly and be directly addressed without the periodic detection
	 *  pass ever happening to re-flag them as recurring, leaving them stuck as
	 *  "Unconfirmed" indefinitely with no visible reason and, until now, no way
	 *  to override it.
	 */
	confirmNpc: (conversationId: string, characterId: string) => typedError<null, MythicError>(__TAURI_INVOKE("confirm_npc", { conversationId, characterId })),
	/**
	 *  Marks an NPC's auto-generated profile as reviewed — clears the "new
	 *  profile" half of the needs-attention indicator's condition.
	 */
	markNpcReviewed: (characterId: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("mark_npc_reviewed", { characterId })),
	/**
	 *  Refreshes a character's description/personality/scenario against how
	 *  they've actually appeared in this conversation — canon facts (settled,
	 *  character-level truth) plus recent dialogue (voice/tone anchor), with
	 *  the character's own current profile passed in so the model refines
	 *  rather than reinvents (and knows to disregard the "just spoke for the
	 *  first time" placeholder as if it were empty). Used by both the manual
	 *  "Refresh from Story" button and the automatic still-placeholder trigger
	 *  in the NPC detection pipeline.
	 * 
	 *  If this character appears in more than just this one conversation, the
	 *  card is deliberately left untouched — see `ProfileRefreshResult::scope`.
	 */
	refreshCharacterProfile: (characterId: string, conversationId: string, systemPrompt: string | null) => typedError<ProfileRefreshResult_Serialize, MythicError>(__TAURI_INVOKE("refresh_character_profile", { characterId, conversationId, systemPrompt })),
	/**
	 *  TEMPORARY Phase-A dev command — runs the NPC detection pipeline directly
	 *  and synchronously (unlike the real pipeline, which always runs as a
	 *  swallowed-error background task) so it can be exercised and verified
	 *  before it's wired into live chat. Remove once Phase B wires automatic
	 *  triggers into `commands::chat`.
	 */
	debugRunNpcDetection: (conversationId: string, aiResponse: string) => typedError<null, MythicError>(__TAURI_INVOKE("debug_run_npc_detection", { conversationId, aiResponse })),
	/**
	 *  Generates a portrait for an NPC via the configured image provider,
	 *  framed from its auto-generated description. Silently skips — returns the
	 *  character unchanged, no error — if no image provider is configured; an
	 *  auto-approved placeholder gradient standing in for a face would be worse
	 *  than no portrait at all.
	 */
	generateNpcPortrait: (characterId: string, conversationId: string, autoApprove: boolean) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("generate_npc_portrait", { characterId, conversationId, autoApprove })),
	/**
	 *  Approves a pending NPC portrait (`portrait_status -> 'approved'`) — the
	 *  avatar image itself is left unchanged.
	 */
	approveNpcPortrait: (characterId: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("approve_npc_portrait", { characterId })),
	/**
	 *  Rejects a pending NPC portrait — clears the avatar entirely (back to the
	 *  initial-circle placeholder) rather than leaving a rejected image in place.
	 */
	rejectNpcPortrait: (characterId: string) => typedError<Character_Serialize, MythicError>(__TAURI_INVOKE("reject_npc_portrait", { characterId })),
	/**
	 *  Returns a multi-character "cast graph" scoped to one conversation — every
	 *  character in that conversation's cast (gallery mains + NPCs) plus their
	 *  combined memories/links. Additive to (not a replacement for) the existing
	 *  per-character `get_memory_graph`, which spans all of one character's
	 *  conversations instead of all characters in one conversation.
	 */
	getCastMemoryGraph: (conversationId: string) => typedError<MemoryGraph_Serialize, MythicError>(__TAURI_INVOKE("get_cast_memory_graph", { conversationId })),
	/**  Creates a new persona from a Character Card V2-shaped payload. */
	createPersona: (name: string, data: JsonValue) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("create_persona", { name, data })),
	/**  Retrieves a single persona by ID. */
	getPersona: (id: string) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("get_persona", { id })),
	/**  Lists all personas, ordered by most recently updated. */
	listPersonas: () => typedError<Persona_Serialize[], MythicError>(__TAURI_INVOKE("list_personas")),
	/**  Updates an existing persona's data. */
	updatePersona: (id: string, name: string | null, data: "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue } | null, avatarPath: string | null) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("update_persona", { id, name, data, avatarPath })),
	/**
	 *  Permanently deletes a persona by ID. Cascade (clearing
	 *  `conversations.persona_id`) is handled by the `cascade_persona_delete`
	 *  SurrealDB event. Only the Trash view should call this — normal deletion
	 *  should call `trash_persona` instead.
	 */
	deletePersona: (id: string) => typedError<null, MythicError>(__TAURI_INVOKE("delete_persona", { id })),
	/**  Moves a persona to Trash (soft delete) — reversible via `restore_persona`. */
	trashPersona: (id: string) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("trash_persona", { id })),
	/**  Restores a trashed persona. */
	restorePersona: (id: string) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("restore_persona", { id })),
	/**
	 *  Generates a portrait for a persona via the configured image provider,
	 *  framed from its description. Silently skips — returns the persona
	 *  unchanged, no error — if no image provider is configured, same as NPC
	 *  portrait generation.
	 * 
	 *  `conversation_id` is optional (personas aren't conversation-scoped —
	 *  one persona may be used across many conversations): when given, the
	 *  AI-Horde image preset is resolved for that conversation; otherwise the
	 *  global default preset is used.
	 */
	generatePersonaPortrait: (personaId: string, conversationId: string | null) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("generate_persona_portrait", { personaId, conversationId })),
	/**
	 *  Imports a persona from a PNG file containing embedded Character Card V2
	 *  data — the same "chara" tEXt-chunk convention as `import_character_card`,
	 *  just landing in the `personas` table and its own `personas/` avatar
	 *  subdirectory instead of `characters`/`avatars/`.
	 */
	importPersonaCard: (filePath: string) => typedError<Persona_Serialize, MythicError>(__TAURI_INVOKE("import_persona_card", { filePath })),
	/**  Sets (or clears, passing `null`) this conversation's chosen persona. */
	setConversationPersona: (conversationId: string, personaId: string | null) => typedError<null, MythicError>(__TAURI_INVOKE("set_conversation_persona", { conversationId, personaId })),
	/**
	 *  Lists everything currently in the Trash across conversations, characters,
	 *  and personas — merged and sorted by deleted_at, most recently trashed
	 *  first.
	 */
	listTrash: () => typedError<TrashItem[], MythicError>(__TAURI_INVOKE("list_trash")),
	/**
	 *  Permanently deletes every item currently in the Trash, across all three
	 *  types. Best-effort per item — one failure is logged and skipped rather
	 *  than aborting the rest of the sweep.
	 */
	emptyTrash: () => typedError<null, MythicError>(__TAURI_INVOKE("empty_trash")),
	/**
	 *  Returns the last `lines` (default 1000, capped at `MAX_LINES`) lines of
	 *  the persisted backend log file, oldest first within that window. Empty
	 *  string (not an error) if the file doesn't exist yet — e.g. right after a
	 *  fresh install before anything's been logged.
	 */
	getBackendLogs: (lines: number | null) => typedError<string, MythicError>(__TAURI_INVOKE("get_backend_logs", { lines })),
	/**
	 *  Returns one page of backend log lines read backward from `cursor` (a byte
	 *  offset into the log file; omit to start at the end — the newest lines).
	 *  Used by the Logging tab's viewer to load the file incrementally as the
	 *  user scrolls up, rather than reading it in full up front: only a bounded
	 *  window at the tail is read per call, growing just enough to cover the
	 *  requested `limit` lines.
	 */
	getBackendLogsPage: (cursor: number | null, limit: number | null) => typedError<LogPage, MythicError>(__TAURI_INVOKE("get_backend_logs_page", { cursor, limit })),
	/**
	 *  Absolute path to the backend log file — shown in the Logging tab so the
	 *  user can locate it directly (e.g. to attach to a bug report) without
	 *  going through Export.
	 */
	getBackendLogPath: () => typedError<string, MythicError>(__TAURI_INVOKE("get_backend_log_path")),
};

/* Types */
/**  Basic app metadata surfaced to the frontend (About screen, etc.). */
export type AppInfo = {
	name: string,
	version: string,
	description: string,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character = Character_Serialize | Character_Deserialize;

/**
 *  A single cast member's portrait, handed to a ComfyUI or WanGP generation
 *  so it can be attached as a reference image. ComfyUI substitutes these into
 *  whichever `{{CHARACTER_IMAGE_n}}` token(s) the user's workflow references
 *  (`providers::comfyui`); WanGP attaches them under whatever field its own
 *  model schema reports for reference images (`providers::wangp`).
 *  `relative_path` is relative to `app_data_dir` (e.g. a character's own
 *  `avatar_path`), the same convention avatars/portraits already use
 *  everywhere else.
 */
export type CharacterImageRef = {
	characterId: string,
	characterName: string,
	relativePath: string,
};

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState = CharacterState_Serialize | CharacterState_Deserialize;

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState_Deserialize = {
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
};

/**  The persisted emotional state of a character within one conversation. */
export type CharacterState_Serialize = {
	id: string,
	character_id: string,
	conversation_id: string,
	/**  0 = devastated, 50 = neutral, 100 = elated */
	mood: number,
	/**  0 = hostile, 50 = wary, 100 = devoted */
	trust: number,
	/**  0 = withdrawn, 50 = engaged, 100 = intense */
	arousal: number,
	/**  Single lowercase word describing the dominant emotion (e.g. "curious") */
	dominant_emotion: string,
	/**  1–2 sentence description of the character's internal state (third person) */
	state_summary: string,
	updated_at: string,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character_Deserialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB */
	data: JsonValue,
	/**  Path to the character's avatar image file (relative to app data dir) */
	avatar_path: string | null,
	created_at?: string,
	updated_at?: string,
	/**
	 *  "gallery" (a real standalone character) or "npc" (auto-generated by
	 *  the story-driven NPC detector, scoped to its originating conversation
	 *  until the user promotes it). Rows predating this field read back as
	 *  "gallery" via the serde default, matching the schema's own default.
	 */
	origin?: string,
	/**
	 *  Only meaningful for auto-generated portraits — "pending_review" means
	 *  the image exists but hasn't been approved by the user yet.
	 */
	portrait_status?: string,
	/**
	 *  False only for a freshly auto-generated NPC profile the user hasn't
	 *  opened yet — drives the needs-attention indicator.
	 */
	profile_reviewed?: boolean,
	/**  Set when the character is in the Trash; None means it's live. */
	deleted_at?: string | null,
};

/**
 *  Database representation of a character.
 *  Stores the full V2 JSON in the `data` field as a native JSON object in SurrealDB.
 */
export type Character_Serialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB */
	data: JsonValue,
	/**  Path to the character's avatar image file (relative to app data dir) */
	avatar_path: string | null,
	created_at: string,
	updated_at: string,
	/**
	 *  "gallery" (a real standalone character) or "npc" (auto-generated by
	 *  the story-driven NPC detector, scoped to its originating conversation
	 *  until the user promotes it). Rows predating this field read back as
	 *  "gallery" via the serde default, matching the schema's own default.
	 */
	origin: string,
	/**
	 *  Only meaningful for auto-generated portraits — "pending_review" means
	 *  the image exists but hasn't been approved by the user yet.
	 */
	portrait_status: string,
	/**
	 *  False only for a freshly auto-generated NPC profile the user hasn't
	 *  opened yet — drives the needs-attention indicator.
	 */
	profile_reviewed: boolean,
	/**  Set when the character is in the Trash; None means it's live. */
	deleted_at: string | null,
};

/**
 *  Tests connectivity to a provider by attempting a health check.
 *  Result of a provider connection test — `ok: false` always comes with a
 *  `detail` explaining *why*, since a bare "unreachable" collapses several
 *  very different failure modes (bad API key, wrong Base URL, the actual
 *  server being down, a timeout, DNS failure...) into one meaningless word
 *  that gives the user nothing to act on.
 */
export type ConnectionTestResult = {
	ok: boolean,
	detail: string | null,
};

/**
 *  Statistics about the context window for observability.
 *  Returned alongside the prompt so callers can log/surface token usage.
 */
export type ContextStats = {
	/**  Total token budget for the context window. */
	total_budget: number,
	/**  Tokens used by fixed layers (system, character, lorebook, memories, emotion, PHI). */
	fixed_tokens: number,
	/**  Tokens used by conversation history (after sliding window). */
	history_tokens: number,
	/**  Tokens used by the rolling summary (0 if no summary yet). */
	summary_tokens: number,
	/**  Total messages in the full conversation branch. */
	total_messages: number,
	/**  Messages included in the sliding window. */
	included_messages: number,
	/**  Messages evicted (not sent to the LLM). */
	evicted_messages: number,
	/**  Tokens used by RAG-retrieved context (0 if RAG disabled or no results). */
	rag_tokens: number,
};

/**  A conversation session between the user and a character. */
export type Conversation = Conversation_Serialize | Conversation_Deserialize;

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter = ConversationCharacter_Serialize | ConversationCharacter_Deserialize;

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter_Deserialize = {
	id: string,
	conversation_id: string,
	character_id: string,
	/**  "primary" | "secondary" | "npc" */
	role: string,
	/**  0-100: how often the AI should include this character's response */
	talkativeness: number,
	/**  Whether the character is currently active in the scene (false = muted) */
	is_active: boolean,
	/**  Character name (denormalized for convenience in prompt building) */
	character_name?: string,
	created_at?: string,
};

/**
 *  A character's membership in a conversation — tracks role, talkativeness, and active status.
 *  Each character in a multi-character conversation gets one record.
 */
export type ConversationCharacter_Serialize = {
	id: string,
	conversation_id: string,
	character_id: string,
	/**  "primary" | "secondary" | "npc" */
	role: string,
	/**  0-100: how often the AI should include this character's response */
	talkativeness: number,
	/**  Whether the character is currently active in the scene (false = muted) */
	is_active: boolean,
	/**  Character name (denormalized for convenience in prompt building) */
	character_name: string,
	created_at: string,
};

/**  A conversation session between the user and a character. */
export type Conversation_Deserialize = {
	id: string,
	title: string,
	/**  The character associated with this conversation */
	character_id: string | null,
	/**  ID of the active (latest) message in the current branch */
	active_message_id?: string | null,
	/**
	 *  Controls how auto-extracted memories are scoped:
	 *  - "character"    — shared across all conversations with this character (default)
	 *  - "conversation" — isolated to this specific conversation only
	 *  - "none"         — auto-save disabled for this conversation
	 */
	memory_scope?: string,
	shared_character_ids?: string | null,
	/**  If this conversation was forked from another, this points to the parent conversation. */
	parent_conversation_id?: string | null,
	/**  The exact message in the parent conversation where the fork happened. */
	branch_point_message_id?: string | null,
	/**
	 *  This conversation's chosen image-generation preset. When unset, scene
	 *  generation falls back to the global default preset (if any), then to
	 *  the image provider's own config.
	 */
	image_preset_id?: string | null,
	/**
	 *  This conversation's chosen persona (the user's stand-in). When unset,
	 *  prompt-building is a complete no-op with respect to persona features
	 *  — no {{user}} substitution, no "About the User" context block.
	 */
	persona_id?: string | null,
	created_at?: string,
	updated_at?: string,
	/**  Set when the conversation is in the Trash; None means it's live. */
	deleted_at?: string | null,
};

/**  A conversation session between the user and a character. */
export type Conversation_Serialize = {
	id: string,
	title: string,
	/**  The character associated with this conversation */
	character_id: string | null,
	/**  ID of the active (latest) message in the current branch */
	active_message_id: string | null,
	/**
	 *  Controls how auto-extracted memories are scoped:
	 *  - "character"    — shared across all conversations with this character (default)
	 *  - "conversation" — isolated to this specific conversation only
	 *  - "none"         — auto-save disabled for this conversation
	 */
	memory_scope: string,
	shared_character_ids: string | null,
	/**  If this conversation was forked from another, this points to the parent conversation. */
	parent_conversation_id: string | null,
	/**  The exact message in the parent conversation where the fork happened. */
	branch_point_message_id: string | null,
	/**
	 *  This conversation's chosen image-generation preset. When unset, scene
	 *  generation falls back to the global default preset (if any), then to
	 *  the image provider's own config.
	 */
	image_preset_id: string | null,
	/**
	 *  This conversation's chosen persona (the user's stand-in). When unset,
	 *  prompt-building is a complete no-op with respect to persona features
	 *  — no {{user}} substitution, no "About the User" context block.
	 */
	persona_id: string | null,
	created_at: string,
	updated_at: string,
	/**  Set when the conversation is in the Trash; None means it's live. */
	deleted_at: string | null,
};

/**
 *  Bundled fields for `create_image_preset` — kept as a struct rather than
 *  individual params since AI Horde quality knobs (clip_skip, post_processing,
 *  hires_fix) pushed this past tauri-specta's ~10-argument function limit.
 */
export type CreateImagePresetFields = {
	model: string | null,
	samplerName: string,
	cfgScale: number | null,
	steps: number,
	karras: boolean,
	style: string | null,
	negativePrompt: string | null,
	isDefault: boolean,
	clipSkip: number | null,
	postProcessing: string[],
	hiresFix: boolean,
	hiresFixDenoisingStrength: number | null,
};

/**  Embedding index status for the frontend Memory settings. */
export type EmbeddingIndexStatus = {
	/**  Total messages across all conversations (or in a specific one) */
	total_messages: number,
	/**  Messages that have embeddings stored */
	embedded_messages: number,
	/**  The model name used for existing embeddings (None if no embeddings exist) */
	index_model: string | null,
	/**  Whether the index needs rebuilding (stored model != selected model) */
	needs_rebuild: boolean,
	/**  Percentage of messages embedded (0-100) */
	coverage_percent: number | null,
	/**  Dimension of existing embeddings (None if no embeddings exist) */
	index_dimension: number | null,
	/**  Dimension of the currently selected embedding model (from known dimensions map) */
	selected_dimension: number | null,
	/**  Whether dimensions mismatch between stored and selected model */
	dimension_mismatch: boolean,
};

/**
 *  Optional knobs for `generate_scene`, bundled into one struct because
 *  tauri-specta's command macro caps out around 10 top-level parameters.
 */
export type GenerateSceneOptions = {
	negativePrompt: string | null,
	width: number | null,
	height: number | null,
	/**
	 *  Takes precedence over both the resolved preset's model and the
	 *  provider's own default. Lets the user pick a different model for one
	 *  generation without editing the preset.
	 */
	modelOverride: string | null,
	/**
	 *  Path (relative to app_data_dir, e.g. a character's avatar_path) to
	 *  use as an img2img reference — anchors the generation to that image
	 *  instead of generating from the text prompt alone.
	 */
	referenceImagePath: string | null,
	/**
	 *  img2img strength when reference_image_path is set: lower keeps the
	 *  reference closer, higher lets the new scene diverge more. Defaults
	 *  to 0.6 (a moderate anchor) if unset.
	 */
	denoisingStrength: number | null,
	/**
	 *  Mirrors the user's "Allow Mature Content" setting — sent as AI
	 *  Horde's `nsfw` request flag so an ordinary (non-explicit) character
	 *  description doesn't get false-positive censored by an overzealous
	 *  worker-side classifier. Defaults to false (strict) if unset.
	 */
	allowNsfw: boolean | null,
	/**
	 *  Cast portraits to feed into a ComfyUI workflow's `{{CHARACTER_IMAGE_n}}`
	 *  tokens (see `providers::comfyui`) — ignored by every other adapter,
	 *  which has no multi-image mechanism. Unlike `reference_image_path`
	 *  (AI Horde's single img2img anchor), this supports any number of
	 *  characters, limited only by how many `{{CHARACTER_IMAGE_n}}` tokens
	 *  the user's own workflow references.
	 */
	characterImages?: CharacterImageRef[] | null,
};

/**
 *  Optional knobs for `generate_video_scene` — same shape/intent as
 *  `GenerateSceneOptions`, minus the image-only fields (`reference_image_path`/
 *  `denoising_strength` are AI Horde's img2img mechanism, which has no video
 *  equivalent here) and plus video-specific ones (`duration_seconds`, `fps`).
 */
export type GenerateVideoOptions = {
	negativePrompt: string | null,
	width: number | null,
	height: number | null,
	durationSeconds: number | null,
	fps: number | null,
	modelOverride: string | null,
	allowNsfw: boolean | null,
	/**
	 *  Cast portraits for multi-character reference — see `GenerateSceneOptions::character_images`.
	 *  WanGP is currently the only adapter that acts on this for video.
	 */
	characterImages?: CharacterImageRef[] | null,
};

/**
 *  A reusable image-generation style bundle (sampler/cfg/steps/karras,
 *  optional AI Horde named style, optional negative prompt override).
 *  Selectable per-conversation, or applied globally via `is_default`, so
 *  different chats can use different visual styles without editing the
 *  image provider's own connection config.
 */
export type ImagePreset = ImagePreset_Serialize | ImagePreset_Deserialize;

/**
 *  A reusable image-generation style bundle (sampler/cfg/steps/karras,
 *  optional AI Horde named style, optional negative prompt override).
 *  Selectable per-conversation, or applied globally via `is_default`, so
 *  different chats can use different visual styles without editing the
 *  image provider's own connection config.
 */
export type ImagePreset_Deserialize = {
	id: string,
	name: string,
	model: string | null,
	sampler_name: string,
	cfg_scale: number | null,
	steps: number,
	karras: boolean,
	/**
	 *  A named/shared AI Horde style (see aihorde.net styles) — when set,
	 *  overrides model/sampler/cfg_scale/steps/karras/negative_prompt above
	 *  entirely at generation time.
	 */
	style: string | null,
	negative_prompt: string | null,
	/**
	 *  CLIP layers to skip (1-12). Most anime/illustration checkpoints
	 *  (Pony Diffusion V6 XL, AAM XL AnimeMix) are trained expecting 2;
	 *  `None` lets AI Horde apply its own default (1).
	 */
	clip_skip?: number | null,
	/**
	 *  AI Horde post-processors to run, in order — face-fixers (GFPGAN,
	 *  CodeFormers) and/or upscalers (RealESRGAN variants, 4x_AnimeSharp).
	 */
	post_processing?: string[],
	/**
	 *  Re-processes the image at a higher resolution after the base
	 *  generation — the single biggest lever for fixing composition/anatomy
	 *  errors, at the cost of roughly doubling generation time and kudos.
	 */
	hires_fix?: boolean,
	hires_fix_denoising_strength?: number | null,
	is_default: boolean,
	created_at?: string,
};

/**
 *  A reusable image-generation style bundle (sampler/cfg/steps/karras,
 *  optional AI Horde named style, optional negative prompt override).
 *  Selectable per-conversation, or applied globally via `is_default`, so
 *  different chats can use different visual styles without editing the
 *  image provider's own connection config.
 */
export type ImagePreset_Serialize = {
	id: string,
	name: string,
	model: string | null,
	sampler_name: string,
	cfg_scale: number | null,
	steps: number,
	karras: boolean,
	/**
	 *  A named/shared AI Horde style (see aihorde.net styles) — when set,
	 *  overrides model/sampler/cfg_scale/steps/karras/negative_prompt above
	 *  entirely at generation time.
	 */
	style: string | null,
	negative_prompt: string | null,
	/**
	 *  CLIP layers to skip (1-12). Most anime/illustration checkpoints
	 *  (Pony Diffusion V6 XL, AAM XL AnimeMix) are trained expecting 2;
	 *  `None` lets AI Horde apply its own default (1).
	 */
	clip_skip: number | null,
	/**
	 *  AI Horde post-processors to run, in order — face-fixers (GFPGAN,
	 *  CodeFormers) and/or upscalers (RealESRGAN variants, 4x_AnimeSharp).
	 */
	post_processing: string[],
	/**
	 *  Re-processes the image at a higher resolution after the base
	 *  generation — the single biggest lever for fixing composition/anatomy
	 *  errors, at the cost of roughly doubling generation time and kudos.
	 */
	hires_fix: boolean,
	hires_fix_denoising_strength: number | null,
	is_default: boolean,
	created_at: string,
};

/**
 *  A minimal recursive JSON type used purely as a `#[specta(type = JsonValue)]`
 *  override for `serde_json::Value` fields (arbitrary-shape blobs like
 *  character card data, provider config, message metadata).
 * 
 *  specta's own built-in `serde_json::Value` support (`legacy_impls.rs`,
 *  `serde_json` feature) registers it as an *inline* type whose `Array`/
 *  `Object` variants re-expand `Value::definition()` with no cycle-breaking —
 *  genuine infinite recursion on export, unrelated to any real data depth.
 *  A normally-derived enum like this one IS registered as a named/cached
 *  type by the derive macro, so the recursion terminates correctly. The
 *  actual Rust field stays `serde_json::Value`; this type only stands in for
 *  specta's reflection.
 * 
 *  `#[serde(untagged)]` is required so the exported TS type matches the real
 *  wire shape: `serde_json::Value` serializes as plain JSON (a bare number,
 *  string, object, etc.), not as a `{ "Bool": true }`-style tagged variant.
 *  Without it, specta falls back to externally-tagged rendering, producing a
 *  TS type that looks plausible but never matches the actual payload. The
 *  `Serialize`/`Deserialize` derives are never used to move real data (this
 *  type is never constructed) — they exist only so `#[serde(untagged)]` is a
 *  legal attribute here for specta's own (derive-independent) attribute
 *  parsing to read.
 */
export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type LogPage = {
	/**
	 *  Lines within this page, oldest first — same ordering as
	 *  [`get_backend_logs`].
	 */
	lines: string[],
	/**
	 *  Byte offset to pass back as `cursor` to fetch the page immediately
	 *  before this one (older lines). `None` once the start of the file has
	 *  been reached — there is nothing older to load. `u32` (not `u64`,
	 *  which specta's TypeScript export forbids as a bigint-precision risk)
	 *  caps a single log file at ~4GB, far beyond anything this feature
	 *  needs to handle.
	 */
	nextCursor: number | null,
};

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry = LorebookEntry_Serialize | LorebookEntry_Deserialize;

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry_Deserialize = {
	id: string,
	/**  The character this entry belongs to (None = global lorebook) */
	character_id?: string | null,
	/**
	 *  Trigger keywords — entry activates when any keyword is found in chat.
	 *  Stored as native array in SurrealDB.
	 */
	keys: string[],
	/**  The content to inject into the prompt when triggered */
	content: string,
	/**  Whether this entry is active */
	enabled: boolean,
	/**  If true, always injected regardless of keyword matches */
	always_active: boolean,
	/**  Priority level (higher = more important when context is limited) */
	priority: number,
	/**  Order relative to other entries in the prompt */
	insertion_order: number,
	/**  Optional display name for the entry */
	name: string | null,
};

/**
 *  A standalone lorebook entry stored in the database.
 * 
 *  Lorebooks are keyword-triggered world information that gets
 *  injected into the prompt only when relevant keywords appear
 *  in the recent chat history. This keeps the context focused
 *  while allowing rich world-building.
 */
export type LorebookEntry_Serialize = {
	id: string,
	/**  The character this entry belongs to (None = global lorebook) */
	character_id: string | null,
	/**
	 *  Trigger keywords — entry activates when any keyword is found in chat.
	 *  Stored as native array in SurrealDB.
	 */
	keys: string[],
	/**  The content to inject into the prompt when triggered */
	content: string,
	/**  Whether this entry is active */
	enabled: boolean,
	/**  If true, always injected regardless of keyword matches */
	always_active: boolean,
	/**  Priority level (higher = more important when context is limited) */
	priority: number,
	/**  Order relative to other entries in the prompt */
	insertion_order: number,
	/**  Optional display name for the entry */
	name: string | null,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory = Memory_Serialize | Memory_Deserialize;

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph = MemoryGraph_Serialize | MemoryGraph_Deserialize;

/**  One cast member in a multi-character `MemoryGraph`. */
export type MemoryGraphCharacter = {
	id: string,
	name: string,
};

/**  Minimal conversation info for graph rendering. */
export type MemoryGraphConversation = {
	id: string,
	title: string,
	character_id: string,
	memory_count: number,
	/**  If this conversation was branched from another, this is the parent's ID. */
	parent_conversation_id: string | null,
};

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph_Deserialize = {
	character_id: string,
	character_name: string,
	memories: Memory_Deserialize[],
	links: MemoryLink_Deserialize[],
	/**  Conversations that have memories for this character */
	conversations: MemoryGraphConversation[],
	/**
	 *  Populated (one entry per cast member) for a multi-character
	 *  per-conversation "cast graph"; empty for the single-character graph,
	 *  in which case the frontend falls back to `character_id`/`character_name`.
	 */
	characters?: MemoryGraphCharacter[],
};

/**  The full memory graph for a character — used by the frontend graph UI. */
export type MemoryGraph_Serialize = {
	character_id: string,
	character_name: string,
	memories: Memory_Serialize[],
	links: MemoryLink_Serialize[],
	/**  Conversations that have memories for this character */
	conversations: MemoryGraphConversation[],
	/**
	 *  Populated (one entry per cast member) for a multi-character
	 *  per-conversation "cast graph"; empty for the single-character graph,
	 *  in which case the frontend falls back to `character_id`/`character_name`.
	 */
	characters: MemoryGraphCharacter[],
};

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink = MemoryLink_Serialize | MemoryLink_Deserialize;

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink_Deserialize = {
	id: string,
	link_type: string,
	direction: string,
	sync_mode: string,
	linked_memory_id?: string | null,
	created_at?: string,
} & {
	in: string,
} & {
	out: string,
};

/**
 *  A cross-conversation memory sharing link (SurrealDB graph edge).
 * 
 *  Links connect a source memory to a target conversation, creating either
 *  a frozen copy or a live-synced connection. Users configure:
 *  - `link_type`: copy (snapshot) vs sync (live-linked)
 *  - `direction`: one_way (source → target) vs two_way (bidirectional)
 *  - `sync_mode`: auto (system-managed) vs manual (user-triggered)
 */
export type MemoryLink_Serialize = {
	id: string,
	source_memory_id: string,
	target_conversation_id: string,
	link_type: string,
	direction: string,
	sync_mode: string,
	linked_memory_id: string | null,
	created_at: string,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory_Deserialize = {
	id: string,
	character_id?: string | null,
	conversation_id?: string | null,
	content: string,
	source: string,
	/**  Parent memory this was forked/inherited from (None = root) */
	parent_id?: string | null,
	/**  Version counter — increments on each edit */
	version: number,
	/**  Whether this is a character-level "canon" memory (trunk of the tree) */
	is_canon: boolean,
	created_at?: string,
	/**
	 *  Manual importance tier (1-10, default 5/neutral) used to weight
	 *  retrieval ranking alongside semantic relevance and recency.
	 */
	importance?: number,
	/**
	 *  When this memory was last surfaced to the LLM via retrieval — `None`
	 *  if it has never been retrieved (including all rows predating this
	 *  field, which are absent from storage rather than defaulted).
	 */
	last_accessed?: string | null,
	/**  How many times this memory has been surfaced via retrieval. */
	access_count?: number,
};

/**
 *  A persisted memory entry — user-pinned facts or AI-extracted context.
 * 
 *  Memories form a tree structure via `parent_id`:
 *  - Canon memories (`is_canon = true`) are root nodes at the character level
 *  - Conversation memories can inherit from canon via `parent_id`
 *  - Sharing between conversations creates linked copies/syncs
 */
export type Memory_Serialize = {
	id: string,
	character_id: string | null,
	conversation_id: string | null,
	content: string,
	source: string,
	/**  Parent memory this was forked/inherited from (None = root) */
	parent_id: string | null,
	/**  Version counter — increments on each edit */
	version: number,
	/**  Whether this is a character-level "canon" memory (trunk of the tree) */
	is_canon: boolean,
	created_at: string,
	/**
	 *  Manual importance tier (1-10, default 5/neutral) used to weight
	 *  retrieval ranking alongside semantic relevance and recency.
	 */
	importance: number,
	/**
	 *  When this memory was last surfaced to the LLM via retrieval — `None`
	 *  if it has never been retrieved (including all rows predating this
	 *  field, which are absent from storage rather than defaulted).
	 */
	last_accessed: string | null,
	/**  How many times this memory has been surfaced via retrieval. */
	access_count: number,
};

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message = Message_Serialize | Message_Deserialize;

/**
 *  A single image attached to a user message, sent as real multimodal
 *  input to vision-capable models (see `providers::unified::convert_messages`).
 *  Stored in `Message.metadata` as `{"attachments": [MessageAttachment, ...]}`
 *  — `relative_path` follows the same app_data_dir-relative convention as
 *  avatars/portraits/scenes, resolved via `crate::error::resolve_within`.
 */
export type MessageAttachment = {
	relativePath: string,
	mimeType: string,
};

/**  The role of a message sender in a conversation. */
export type MessageRole = 
/**  Message from the user */
"user" | 
/**  Message from the AI character */
"assistant" | 
/**  System-level instruction (not displayed to user) */
"system";

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message_Deserialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**
	 *  Parent message ID — enables conversation branching.
	 *  If None, this is a root message.
	 */
	parent_id?: string | null,
	/**  JSON metadata for attached images, generation params, etc. */
	metadata: JsonValue | null,
	/**
	 *  Character who sent this message (for multi-character conversations).
	 *  None for user messages and single-character conversations.
	 */
	character_id?: string | null,
	/**  Denormalized character name for display (avoids extra lookups). */
	character_name?: string | null,
	created_at?: string,
	/**
	 *  Chain-of-thought/reasoning trace from a reasoning model, kept separate
	 *  from `content` — rendered as a collapsible "thinking" section rather
	 *  than as if the character said it.
	 */
	reasoning?: string | null,
};

/**
 *  A single message within a conversation.
 * 
 *  Messages form a tree structure via `parent_id` to support
 *  conversation branching (forking from any point in history).
 */
export type Message_Serialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**
	 *  Parent message ID — enables conversation branching.
	 *  If None, this is a root message.
	 */
	parent_id: string | null,
	/**  JSON metadata for attached images, generation params, etc. */
	metadata: JsonValue | null,
	/**
	 *  Character who sent this message (for multi-character conversations).
	 *  None for user messages and single-character conversations.
	 */
	character_id: string | null,
	/**  Denormalized character name for display (avoids extra lookups). */
	character_name: string | null,
	created_at: string,
	/**
	 *  Chain-of-thought/reasoning trace from a reasoning model, kept separate
	 *  from `content` — rendered as a collapsible "thinking" section rather
	 *  than as if the character said it.
	 */
	reasoning: string | null,
};

/**  A single model entry returned by `list_all_models`. */
export type ModelEntry = {
	model_id: string,
	provider_id: string,
	provider_name: string,
	adapter: string,
	model_type: string,
	context_length: number | null,
	enabled: boolean,
	display_name: string | null,
	description: string | null,
	pricing_prompt: string | null,
	pricing_completion: string | null,
	is_free: boolean,
	max_completion_tokens: number | null,
	input_modalities: string[],
	output_modalities: string[],
	supports_tools: boolean,
	supports_vision: boolean,
	supports_reasoning: boolean,
	/**  Embedding vector dimensions (populated for embedding models) */
	embedding_dimensions: number | null,
	/**
	 *  True when this model is enabled locally but no longer appears in the
	 *  provider's live catalog (e.g. delisted upstream). Stale entries carry
	 *  no fetched metadata (pricing, context length, etc.) — just enough to
	 *  show the user what's enabled and let them turn it off.
	 */
	is_stale: boolean,
	/**
	 *  Model architecture (e.g. "stable diffusion 1", "stable_cascade") —
	 *  only populated for AI Horde image models.
	 */
	baseline: string | null,
	/**
	 *  Whether this model reliably supports img2img on AI Horde. Derived
	 *  from `baseline`, not a literal per-model API flag — img2img is a
	 *  generic diffusion capability, but newer architectures (Flux, Stable
	 *  Cascade) are documented as unreliable/unsupported for it.
	 */
	img2img_supported: boolean | null,
	/**  Whether this is a dedicated inpainting-specialized checkpoint. */
	inpainting: boolean | null,
};

/**
 *  Mirrors the exact `{ error, message }` wire shape produced by
 *  `MythicError`'s custom `Serialize` impl above — exists solely so
 *  `MythicError` can implement `specta::Type` by delegating to it.
 * 
 *  Every Tauri command returns `Result<T, MythicError>`; specta's blanket
 *  impl for async function results requires the whole `Result<T, E>` to
 *  implement `Type`, which in turn requires *both* T and E to implement it.
 *  Without this, every async command fails to satisfy `FunctionResult` —
 *  a runtime-of-macro-expansion error, not something `cargo check` on the
 *  type alone would reveal, since compiling this file in isolation is fine.
 */
export type MythicError = {
	error: string,
	message: string,
};

/**
 *  A user-controlled persona — the player's own stand-in for a conversation.
 *  Shares the same CharacterCardV2-shaped `data` JSON as `characters`
 *  (see `models::character::CharacterCardV2`/`CharacterData`), but carries
 *  none of the NPC-pipeline-only fields (`origin`/`portrait_status`/
 *  `profile_reviewed`) since every persona is user-facing by definition.
 */
export type Persona = Persona_Serialize | Persona_Deserialize;

/**
 *  A user-controlled persona — the player's own stand-in for a conversation.
 *  Shares the same CharacterCardV2-shaped `data` JSON as `characters`
 *  (see `models::character::CharacterCardV2`/`CharacterData`), but carries
 *  none of the NPC-pipeline-only fields (`origin`/`portrait_status`/
 *  `profile_reviewed`) since every persona is user-facing by definition.
 */
export type Persona_Deserialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB. */
	data: JsonValue,
	/**  Path to the persona's avatar image file (relative to app data dir). */
	avatar_path: string | null,
	created_at?: string,
	updated_at?: string,
	/**  Set when the persona is in the Trash; None means it's live. */
	deleted_at?: string | null,
};

/**
 *  A user-controlled persona — the player's own stand-in for a conversation.
 *  Shares the same CharacterCardV2-shaped `data` JSON as `characters`
 *  (see `models::character::CharacterCardV2`/`CharacterData`), but carries
 *  none of the NPC-pipeline-only fields (`origin`/`portrait_status`/
 *  `profile_reviewed`) since every persona is user-facing by definition.
 */
export type Persona_Serialize = {
	id: string,
	name: string,
	spec: string,
	/**  Full Character Card V2 JSON, stored as native JSON in SurrealDB. */
	data: JsonValue,
	/**  Path to the persona's avatar image file (relative to app data dir). */
	avatar_path: string | null,
	created_at: string,
	updated_at: string,
	/**  Set when the persona is in the Trash; None means it's live. */
	deleted_at: string | null,
};

/**
 *  Outcome of [`refresh_character_profile`] — the frontend uses `scope` to
 *  tell the user which thing actually happened, since a shared character's
 *  card is deliberately left untouched (see the matching comment below).
 */
export type ProfileRefreshResult = ProfileRefreshResult_Serialize | ProfileRefreshResult_Deserialize;

/**
 *  Outcome of [`refresh_character_profile`] — the frontend uses `scope` to
 *  tell the user which thing actually happened, since a shared character's
 *  card is deliberately left untouched (see the matching comment below).
 */
export type ProfileRefreshResult_Deserialize = {
	character: Character_Deserialize,
	/**
	 *  "character" — the card's description/personality/scenario were
	 *  updated directly (this character only appears in this conversation).
	 *  "memory" — this character is shared across multiple conversations,
	 *  so the refresh was saved as a conversation-scoped memory instead of
	 *  touching the shared card, to avoid one story's details bleeding into
	 *  another conversation's version of the same character. `character` in
	 *  this case is returned unchanged.
	 */
	scope: string,
};

/**
 *  Outcome of [`refresh_character_profile`] — the frontend uses `scope` to
 *  tell the user which thing actually happened, since a shared character's
 *  card is deliberately left untouched (see the matching comment below).
 */
export type ProfileRefreshResult_Serialize = {
	character: Character_Serialize,
	/**
	 *  "character" — the card's description/personality/scenario were
	 *  updated directly (this character only appears in this conversation).
	 *  "memory" — this character is shared across multiple conversations,
	 *  so the refresh was saved as a conversation-scoped memory instead of
	 *  touching the shared card, to avoid one story's details bleeding into
	 *  another conversation's version of the same character. `character` in
	 *  this case is returned unchanged.
	 */
	scope: string,
};

/**  The specific adapter implementation for a provider. */
export type ProviderAdapter = 
/**  Local Ollama instance */
"ollama" | 
/**  OpenRouter API aggregator */
"open_router" | 
/**  Generic OpenAI-compatible API (works with LM Studio, KoboldCPP, vLLM, etc.) */
"open_ai_compatible" | 
/**  SiliconFlow API (LLM + Image + Video) */
"silicon_flow" | 
/**  Hugging Face Inference API */
"hugging_face" | 
/**  Local ComfyUI instance for image/video generation */
"comfy_ui" | 
/**
 *  Local WanGP (Wan2GP) instance for image/video generation, reached over
 *  its MCP server (streamable-http transport) — see `providers::wangp`.
 *  Built for weaker hardware than ComfyUI typically needs.
 */
"wan_gp" | 
/**
 *  AI Horde (formerly Stable Horde) — free, crowdsourced, asynchronous
 *  image generation cluster. Works anonymously (no signup) via the
 *  well-known "0000000000" API key, though registered keys get queue
 *  priority through the kudos system.
 */
"ai_horde" | 
/**  Anthropic API (Claude models) */
"anthropic" | 
/**  Google Gemini API */
"gemini" | 
/**  Cohere API (Command R+) */
"cohere" | 
/**  DeepSeek API */
"deep_seek" | 
/**  Groq API (fast inference) */
"groq" | 
/**  Perplexity API (search-augmented) */
"perplexity" | 
/**  xAI API (Grok models) */
"xai" | 
/**  Hyperbolic API */
"hyperbolic" | 
/**  Moonshot API (Kimi) */
"moonshot" | 
/**  Together API (open-source models) */
"together";

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig_Deserialize = {
	id: string,
	/**  Human-readable name (e.g., "My Local Ollama", "OpenRouter Free") */
	name: string,
	/**  What this provider does */
	provider_type: ProviderType,
	/**  Which adapter implementation to use */
	adapter: ProviderAdapter,
	/**
	 *  Adapter-specific configuration as native JSON.
	 * 
	 *  For Ollama: `{ "base_url": "http://localhost:11434" }`
	 *  For OpenRouter: `{ "api_key": "sk-...", "model": "meta-llama/llama-4-maverick" }`
	 *  For OpenAI-compat: `{ "base_url": "...", "api_key": "...", "model": "..." }`
	 *  For ComfyUI: `{ "base_url": "http://localhost:8188", "workflow": "..." }` — `workflow`
	 *  is the user's own exported (API-format) workflow JSON, stored as a raw string and
	 *  parsed at generation time. It may contain `{{POSITIVE_PROMPT}}`, `{{NEGATIVE_PROMPT}}`,
	 *  `{{SEED}}`, `{{WIDTH}}`, `{{HEIGHT}}`, and `{{CHARACTER_IMAGE_1..N}}` placeholder tokens —
	 *  see `providers::comfyui::substitute_placeholders`.
	 *  For WanGP: `{ "base_url": "http://127.0.0.1:7866", "model": "qwen_image_20B" }` —
	 *  `base_url` points at the WanGP MCP server (`/mcp` is appended at connect time). `model`
	 *  is the same generic "Default Model" field every non-LLM adapter uses; WanGP treats
	 *  whatever's in it as one of its own model identifiers (e.g. `qwen_image_20B` for images,
	 *  `ltx2_22B_distilled` for video). A single WanGP instance serving both image and video
	 *  needs two separate `ProviderConfig` rows (one per `provider_type`) at the same
	 *  `base_url` — see `providers::wangp`.
	 */
	config: JsonValue,
	/**  Whether this is the default provider for its type */
	is_default: boolean,
};

/**
 *  Configuration for a specific AI provider connection.
 * 
 *  Stored in the database and used to initialize provider instances
 *  at runtime. The `config` field holds adapter-specific JSON settings.
 */
export type ProviderConfig_Serialize = {
	id: string,
	/**  Human-readable name (e.g., "My Local Ollama", "OpenRouter Free") */
	name: string,
	/**  What this provider does */
	provider_type: ProviderType,
	/**  Which adapter implementation to use */
	adapter: ProviderAdapter,
	/**
	 *  Adapter-specific configuration as native JSON.
	 * 
	 *  For Ollama: `{ "base_url": "http://localhost:11434" }`
	 *  For OpenRouter: `{ "api_key": "sk-...", "model": "meta-llama/llama-4-maverick" }`
	 *  For OpenAI-compat: `{ "base_url": "...", "api_key": "...", "model": "..." }`
	 *  For ComfyUI: `{ "base_url": "http://localhost:8188", "workflow": "..." }` — `workflow`
	 *  is the user's own exported (API-format) workflow JSON, stored as a raw string and
	 *  parsed at generation time. It may contain `{{POSITIVE_PROMPT}}`, `{{NEGATIVE_PROMPT}}`,
	 *  `{{SEED}}`, `{{WIDTH}}`, `{{HEIGHT}}`, and `{{CHARACTER_IMAGE_1..N}}` placeholder tokens —
	 *  see `providers::comfyui::substitute_placeholders`.
	 *  For WanGP: `{ "base_url": "http://127.0.0.1:7866", "model": "qwen_image_20B" }` —
	 *  `base_url` points at the WanGP MCP server (`/mcp` is appended at connect time). `model`
	 *  is the same generic "Default Model" field every non-LLM adapter uses; WanGP treats
	 *  whatever's in it as one of its own model identifiers (e.g. `qwen_image_20B` for images,
	 *  `ltx2_22B_distilled` for video). A single WanGP instance serving both image and video
	 *  needs two separate `ProviderConfig` rows (one per `provider_type`) at the same
	 *  `base_url` — see `providers::wangp`.
	 */
	config: JsonValue,
	/**  Whether this is the default provider for its type */
	is_default: boolean,
};

/**  The type of AI capability a provider offers. */
export type ProviderType = 
/**  Text generation / chat completion */
"llm" | 
/**  Image generation */
"image" | 
/**  Video generation */
"video";

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene = Scene_Serialize | Scene_Deserialize;

/**
 *  One cast member available as a portrait-reference source for scene
 *  generation — the primary character plus everyone in this conversation's
 *  `conversation_characters` roster (any role, including still-"Unconfirmed"
 *  transients; the frontend decides what to show/select).
 */
export type SceneCastMember = {
	characterId: string,
	name: string,
	avatarPath: string | null,
	/**
	 *  "primary" for the conversation's own character, otherwise whatever
	 *  `conversation_characters.role` holds ("secondary" | "npc" | "transient").
	 */
	role: string,
};

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState = SceneState_Serialize | SceneState_Deserialize;

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState_Deserialize = {
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present?: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at?: string,
};

/**
 *  Dynamic scene state for a conversation — tracks location, time, weather,
 *  characters present, and ambient atmosphere. Updated automatically after
 *  each AI response via the scene extraction engine.
 */
export type SceneState_Serialize = {
	id: string,
	conversation_id: string,
	location_name: string,
	location_description: string,
	/**  morning | midday | afternoon | evening | night | late_night | dawn | unspecified */
	time_period: string,
	/**  clear | cloudy | raining | storming | snowing | foggy | windy */
	weather: string,
	/**  Names of characters currently present in the scene */
	characters_present: string[],
	ambient_details: string,
	/**  tense | calm | romantic | mysterious | dangerous | joyful | melancholic | neutral */
	scene_mood: string,
	updated_at: string,
};

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene_Deserialize = {
	id: string,
	conversation_id: string,
	message_id?: string | null,
	media_type: string,
	prompt: string,
	file_path: string,
	caption: string | null,
	metadata: JsonValue | null,
	created_at?: string,
};

/**  A generated or imported scene (image/video) tied to a conversation. */
export type Scene_Serialize = {
	id: string,
	conversation_id: string,
	message_id: string | null,
	media_type: string,
	prompt: string,
	file_path: string,
	caption: string | null,
	metadata: JsonValue | null,
	created_at: string,
};

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult = SearchResult_Serialize | SearchResult_Deserialize;

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult_Deserialize = {
	message_id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**  Snippet with `<mark>` tags around matched terms */
	snippet: string,
	conversation_title: string,
	character_name: string | null,
	created_at?: string,
};

/**
 *  A search result from full-text message search.
 * 
 *  Contains the matched message plus context about the conversation
 *  and character it belongs to, along with a highlighted snippet.
 */
export type SearchResult_Serialize = {
	message_id: string,
	conversation_id: string,
	role: MessageRole,
	content: string,
	/**  Snippet with `<mark>` tags around matched terms */
	snippet: string,
	conversation_title: string,
	character_name: string | null,
	created_at: string,
};

/**
 *  The IDs of the user/assistant message pair created by `send_message`,
 *  `retry_failed_message`, or `regenerate_message` — the frontend uses
 *  these to attach the streamed response to the right message bubbles.
 */
export type SendMessageResult = {
	user_message_id: string,
	assistant_message_id: string,
};

/**
 *  A single row in the unified Trash view. `item_type` is one of
 *  "conversation" | "character" | "persona" — the frontend uses it to pick
 *  the right restore/delete-forever command and display treatment.
 */
export type TrashItem = {
	id: string,
	item_type: string,
	name: string,
	avatar_path: string | null,
	deleted_at: string,
};

/**
 *  Bundled fields for `update_image_preset` — same "None (unsent) means
 *  leave as-is" convention as `ImagePresetRepo::update`; for `clip_skip`,
 *  `0` clears it back to "no override" (valid range is 1-12).
 */
export type UpdateImagePresetFields = {
	name: string | null,
	model: string | null,
	samplerName: string | null,
	cfgScale: number | null,
	steps: number | null,
	karras: boolean | null,
	style: string | null,
	negativePrompt: string | null,
	clipSkip: number | null,
	postProcessing: string[] | null,
	hiresFix: boolean | null,
	hiresFixDenoisingStrength: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

